"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {download,csv,qty,dt} from "@/app/kho-ui";
import {normalize} from "@/lib/inventory";
// Report rows contain distinct fields for stock, counts, invoices and receipts.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row=Record<string,any>;
type Report={generatedAt:string;locations:{id:string;name:string}[];stock:Row[];invoices:Row[];unlinkedReceipts:Row[];summary:Record<string,number>};
const labels:Record<string,string>={not_counted:"Chưa kiểm kê thực tế",matched:"Khớp",variance:"Có chênh lệch",no_receipt:"Chưa gắn phiếu nhập",unknown:"Chưa đủ dữ liệu",extra_receipt:"Phiếu nhập có hàng ngoài hóa đơn",reversed:"Phiếu nhập đã đảo"};
const fmt=(n:number|null|undefined)=>n==null?"—":qty(n);
export default function ReviewClient({role,displayName}:{role:"owner"|"viewer";displayName:string}){
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(""),[tab,setTab]=useState<"stock"|"count"|"invoice"|"unlinked">("stock"),[area,setArea]=useState("all"),[search,setSearch]=useState(""),[issues,setIssues]=useState(false);
 const [viewers,setViewers]=useState<Row[]>([]),[newName,setNewName]=useState(""),[credential,setCredential]=useState<Row|null>(null),[accountError,setAccountError]=useState(""),[working,setWorking]=useState(false);
 async function reload(){try{const r=await fetch("/api/review",{cache:"no-store"}),out=await r.json() as Report&{error?:string};if(!r.ok)throw Error(out.error);setReport(out);setError("");}catch(e){setError(e instanceof Error?e.message:"Không thể tải báo cáo.");}}
 async function loadViewers(){if(role!=="owner")return;try{const r=await fetch("/api/viewers",{cache:"no-store"}),out=await r.json() as {error?:string;viewers:Row[]};if(!r.ok)throw Error(out.error);setViewers(out.viewers);}catch(e){setAccountError(e instanceof Error?e.message:"Không thể tải tài khoản.");}}
 useEffect(()=>{const controller=new AbortController();
  fetch("/api/review",{cache:"no-store",signal:controller.signal}).then(async r=>{const out=await r.json() as Report&{error?:string};if(!r.ok)throw Error(out.error);setReport(out);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Không thể tải báo cáo.");});
  if(role==="owner")fetch("/api/viewers",{cache:"no-store",signal:controller.signal}).then(async r=>{const out=await r.json() as {error?:string;viewers:Row[]};if(!r.ok)throw Error(out.error);setViewers(out.viewers);}).catch(e=>{if(!controller.signal.aborted)setAccountError(e instanceof Error?e.message:"Không thể tải tài khoản.");});
  return()=>controller.abort();
 },[role]);
 const locations=useMemo(()=>report?.locations.map(l=>[l.id,l.name])||[],[report]);
 const match=(r:Row)=>normalize([r.item,r.itemName,r.locationName,r.invoiceNumber,r.supplier,r.number].filter(Boolean).join(" ")).includes(normalize(search));
 const stock=report?.stock.filter(r=>(area==="all"||r.location===area)&&match(r)&&(!issues||r.status!=="matched"))||[];
 const counts=stock.filter(r=>r.count||!issues);
 const invoice=report?.invoices.filter(r=>(area==="all"||r.locationIds.includes(area))&&match(r)&&(!issues||r.status!=="matched"||r.supplierWarning))||[];
 const unlinked=report?.unlinkedReceipts.filter(r=>(area==="all"||r.location===area)&&match(r))||[];
 function exportCsv(){if(!report)return;
  const rows=tab==="stock"?[["Khu","Mã hàng","Tên hàng","Tình trạng","Lô","HSD","Tồn ghi sổ","ĐVT","Nhập ban đầu từ file","Kiểm kê thực tế gần nhất","Ngày kiểm kê","Chênh lệch lúc kiểm kê","Phát sinh sau kiểm kê","Trạng thái"],...stock.map(r=>[r.locationName,r.item,r.itemName,r.condition,r.lot,r.expiry,r.quantity,r.unit,r.openingSource,r.count?.quantity,r.count?.date,r.count?.difference,r.count?.movementSince,labels[r.status]])]:
   tab==="count"?[["Khu","Mã hàng","Tên hàng","Lô","Sổ trước kiểm kê","Thực đếm","Chênh lệch","Phát sinh sau kiểm kê","Tồn hiện tại","ĐVT","Phiếu kiểm kê","Ngày","Trạng thái"],...counts.map(r=>[r.locationName,r.item,r.itemName,r.lot,r.count?.before,r.count?.quantity,r.count?.difference,r.count?.movementSince,r.quantity,r.unit,r.count?.number,r.count?.date,labels[r.status]])]:
   tab==="invoice"?[["Chứng từ mua","Ngày","NCC","Số NCC","Phiếu nhập","Khu nhận","Mã hàng","Tên hàng","SL hóa đơn","SL phiếu nhập cùng đơn vị","Chênh lệch nhập trừ hóa đơn","Đơn vị so sánh","Trạng thái","Cần kiểm tra tên NCC"],...invoice.map(r=>[r.invoiceNumber,r.invoiceDate,r.supplier,r.reference,r.receiptNumbers.join("; "),r.locationNames.join("; "),r.item,r.itemName,r.billed,r.received,r.difference,r.unit,labels[r.status],r.supplierWarning?"Có":"Không"])]:
   [["Phiếu nhập","Ngày","NCC","Khu nhận","Mã hàng","Tên hàng","SL","ĐVT"],...unlinked.map(r=>[r.number,r.date,r.supplier,r.locationName,r.item,r.itemName,r.quantity,r.unit])];
  download("doi-chieu-kho-"+tab+"-"+new Date().toISOString().slice(0,10)+".csv",csv(rows),"text/csv;charset=utf-8");
 }
 async function account(action:"create"|"revoke",id?:string){setWorking(true);setAccountError("");try{const r=await fetch("/api/viewers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id,displayName:newName})}),out=await r.json() as {error?:string;viewer:Row;password:string};if(!r.ok)throw Error(out.error);if(action==="create"){setCredential({username:out.viewer.username,password:out.password,displayName:out.viewer.displayName});setNewName("");}await loadViewers();}catch(e){setAccountError(e instanceof Error?e.message:"Không thể cập nhật.");}finally{setWorking(false);}}
 return <main className="app-main"><div className="no-print flex flex-wrap justify-between items-center gap-3 mb-6"><div><h1 className="page-title">Báo cáo kho để đối chiếu</h1><p className="subtle">{displayName} · Số liệu tại {report?new Date(report.generatedAt).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"}):"đang tải"}</p></div><div className="flex flex-wrap gap-2">{role==="owner"&&<Button variant="outline" asChild><Link href="/">Về trang quản lý</Link></Button>}<Button variant="outline" onClick={()=>void reload()}>Cập nhật</Button><form action="/api/auth/logout" method="post"><Button variant="outline" type="submit">Đăng xuất</Button></form></div></div>
 {error&&<p role="alert" className="panel text-red-700 mb-4">{error}</p>}
 {report&&<><div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-3 mb-6">{[["Dòng tồn",report.summary.stockLines],["Mã chưa có số tồn",report.summary.itemsWithoutBalance],["Chưa kiểm kê thực tế",report.summary.uncounted],["Dòng kiểm kê lệch",report.summary.countVariances],["Dòng hóa đơn cần xem",report.summary.invoiceIssues]].map(([label,value])=><div className="panel" key={label}><span className="subtle">{label}</span><strong className="block text-2xl mt-1">{value}</strong></div>)}</div>
 <p className="panel mb-5 text-sm">Tồn hiện tại là số ghi sổ sau nhập, chuyển khu, tiêu hao và kiểm kê. Mã chưa có số tồn chưa được tự coi là 0. “Nhập ban đầu từ file” là mốc chuyển dữ liệu cho cả mặt hàng tại khu, không phải hóa đơn hoặc kết quả đếm thực tế; nếu có nhiều lô, mốc này chỉ hiện ở dòng đầu. Chỉ hóa đơn đã gắn phiếu nhập mới có thể kiểm tra số giao; người xem vẫn cần đối chiếu bản gốc NCC khi cần xác nhận pháp lý.</p>
 <div className="no-print flex flex-wrap gap-2 mb-4">{[["stock","Tồn theo khu"],["count","Kiểm kê so với sổ"],["invoice","Hóa đơn ↔ phiếu nhập"],["unlinked","Phiếu nhập chưa gắn hóa đơn"]].map(([key,label])=><Button key={key} variant={tab===key?"default":"outline"} onClick={()=>setTab(key as typeof tab)}>{label}</Button>)}</div>
 <div className="no-print grid sm:grid-cols-[1fr_200px_auto_auto_auto] gap-2 mb-4"><Input aria-label="Tìm hàng hoặc chứng từ" placeholder="Tìm hàng, mã, khu, NCC…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Lọc khu" className="border rounded-lg px-3 bg-white" value={area} onChange={e=>setArea(e.target.value)}><option value="all">Tất cả khu</option>{locations.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={issues} onChange={e=>setIssues(e.target.checked)}/> Cần xem lại</label><Button variant="outline" onClick={exportCsv}>Xuất CSV</Button><Button variant="outline" onClick={()=>window.print()}>In / PDF</Button></div>
 <section className="panel p-0 overflow-x-auto mb-6"><h2 className="font-semibold px-5 pt-5 pb-3">{{stock:"Tồn hiện tại theo khu",count:"Lần kiểm kê gần nhất theo hàng, khu và lô",invoice:"Số trên chứng từ mua so với số nhập kho",unlinked:"Đã nhập kho nhưng chưa gắn chứng từ mua"}[tab]}</h2><table className="w-full text-sm"><thead><tr className="border-y bg-slate-50 text-left">{(tab==="stock"?["Khu / hàng","Tồn ghi sổ","Nhập ban đầu","Kiểm kê thực tế","Trạng thái"]:tab==="count"?["Khu / hàng","Sổ trước","Thực đếm","Chênh lệch","Sau kiểm kê","Tồn hiện tại","Phiếu / ngày"]:tab==="invoice"?["Chứng từ / NCC","Hàng hóa","Hóa đơn","Đã nhập","Chênh lệch","Trạng thái"]:["Phiếu / NCC","Khu nhận","Hàng hóa","Số nhập"]).map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>
 {tab==="stock"&&stock.map((r,i)=><tr className="border-b" key={i}><td className="p-3"><b>{r.itemName}</b><p className="subtle">{r.locationName} · {r.item}{r.lot?" · Lô "+r.lot:""}{r.condition==="damaged"?" · Hỏng":""}</p></td><td className="p-3 whitespace-nowrap"><b>{fmt(r.quantity)} {r.unit}</b></td><td className="p-3">{fmt(r.openingSource)}</td><td className="p-3">{r.count?<>{fmt(r.count.quantity)}<p className="subtle">{dt(r.count.date)} · Sau đó {r.count.movementSince>=0?"+":""}{fmt(r.count.movementSince)}</p></>:"Chưa đếm"}</td><td className="p-3"><span className={"pill "+(r.status==="matched"?"good":r.status==="variance"?"bad":"warn")}>{r.status==="matched"?"Khớp lúc kiểm kê":labels[r.status]}</span></td></tr>)}
 {tab==="count"&&counts.map((r,i)=><tr className="border-b" key={i}><td className="p-3"><b>{r.itemName}</b><p className="subtle">{r.locationName} · {r.item}{r.lot?" · Lô "+r.lot:""}</p></td><td className="p-3">{fmt(r.count?.before)}</td><td className="p-3">{fmt(r.count?.quantity)} {r.unit}</td><td className="p-3">{r.count?fmt(r.count.difference):labels.not_counted}</td><td className="p-3">{fmt(r.count?.movementSince)}</td><td className="p-3"><b>{fmt(r.quantity)} {r.unit}</b></td><td className="p-3">{r.count?<>{r.count.number}<p className="subtle">{dt(r.count.date)}</p></>:"—"}</td></tr>)}
 {tab==="invoice"&&invoice.map((r,i)=><tr className="border-b" key={i}><td className="p-3"><b>{r.invoiceNumber}</b><p className="subtle">{r.supplier} · {dt(r.invoiceDate)}</p><p className="subtle">Nhập hàng này: {r.receiptNumbers.join(", ")||(r.status==="no_receipt"?"chưa gắn phiếu":"không có trên phiếu đã gắn")}</p><p className="subtle">Khu: {r.locationNames.join(", ")||"chưa rõ"}</p></td><td className="p-3"><b>{r.itemName}</b><p className="subtle">{r.item||"Chưa gắn mã hàng"}</p></td><td className="p-3">{fmt(r.billed)} {r.unit}</td><td className="p-3">{fmt(r.received)} {r.unit}</td><td className="p-3">{fmt(r.difference)}</td><td className="p-3"><span className={"pill "+(r.status==="matched"?"good":r.status==="variance"?"bad":"warn")}>{labels[r.status]}</span>{r.supplierWarning&&<p className="text-amber-800 text-xs mt-1">Kiểm tra tên NCC trên phiếu nhập</p>}</td></tr>)}
 {tab==="unlinked"&&unlinked.map((r,i)=><tr className="border-b" key={i}><td className="p-3"><b>{r.number}</b><p className="subtle">{r.supplier} · {dt(r.date)}</p></td><td className="p-3">{r.locationName}</td><td className="p-3">{r.itemName}<p className="subtle">{r.item}</p></td><td className="p-3">{fmt(r.quantity)} {r.unit}</td></tr>)}
 </tbody></table>{(tab==="stock"?stock:tab==="count"?counts:tab==="invoice"?invoice:unlinked).length===0&&<p className="p-5 subtle">Không có dòng phù hợp.</p>}</section></>}
 {role==="owner"&&<section className="panel no-print"><h2 className="text-lg font-semibold">Tài khoản chỉ xem</h2><p className="subtle mb-4">Cấp tài khoản riêng để người nhận xem báo cáo. Mật khẩu chỉ hiện một lần; thu hồi sẽ chặn phiên đăng nhập hiện tại.</p><div className="flex flex-wrap gap-2 mb-4"><Input className="max-w-72" aria-label="Tên người xem" placeholder="Tên người xem" value={newName} maxLength={100} onChange={e=>setNewName(e.target.value)}/><Button disabled={working||!newName.trim()} onClick={()=>void account("create")}>Tạo tài khoản xem</Button></div>{credential&&<div className="bg-amber-50 border border-amber-200 p-4 rounded-lg mb-4"><b>Gửi riêng cho {credential.displayName}</b><p>Trang: {typeof window!=="undefined"?window.location.origin:""}/login</p><p>Tên đăng nhập: <b>{credential.username}</b></p><p>Mật khẩu: <b>{credential.password}</b></p><p className="text-sm">Sao chép ngay; hệ thống không hiển thị lại mật khẩu.</p><Button variant="outline" onClick={()=>setCredential(null)}>Đã lưu</Button></div>}{accountError&&<p role="alert" className="text-red-700">{accountError}</p>}<div className="divide-y">{viewers.map(v=><div className="py-3 flex flex-wrap justify-between gap-2" key={v.id}><span>{v.displayName} <span className="subtle">({v.username})</span></span><Button variant="outline" size="sm" disabled={working} onClick={()=>{if(window.confirm("Thu hồi tài khoản "+v.displayName+"?"))void account("revoke",v.id);}}>Thu hồi</Button></div>)}</div></section>}
 </main>;
}
