"use client";
import {useEffect,useState,useRef} from "react";
import {Package,LayoutDashboard,FilePlus2,Boxes,ClipboardCheck,History,BookOpen,SlidersHorizontal,Database,ArrowDownToLine,ArrowRightLeft,Plus,RefreshCw,ShieldCheck,ArrowUpRight,AlertTriangle,ChevronRight,LogOut,TrendingUp} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarGroup,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from "@/components/ui/sidebar";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import VoucherForm,{newVoucher} from "./voucher-form";
import {InventoryView,CatalogView,SettingsView,stockRows} from "./stock-views";
import {HistoryView,DataView} from "./history-views";
import {SuppliersView,PurchasesView} from "./commerce-views";
import {AnalyticsView} from "./analytics-views";
import {Heading,Empty,dt,money} from "./kho-ui";
import {TYPES,normalize,today,type State,type TxType} from "@/lib/inventory";
const navigation=[["home","Tổng quan",LayoutDashboard],["voucher","Lập phiếu",FilePlus2],["stock","Tồn kho",Boxes],["count","Kiểm kê",ClipboardCheck],["analytics","Phân tích luồng hàng",TrendingUp],["history","Phiếu & lịch sử",History],["suppliers","Nhà cung cấp",BookOpen],["purchases","Mua hàng & công nợ",FilePlus2],["catalog","Danh mục hàng",BookOpen],["data","Dữ liệu & báo cáo",Database],["settings","Thiết lập",SlidersHorizontal]] as const;
function Navigation({tab,go}:{tab:string;go:(t:string)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{navigation.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton className="h-12 px-3 text-[15px]" isActive={tab===id} onClick={()=>{go(id);setOpenMobile(false);}}><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>;}
export default function Application(){
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(""),[tab,setTab]=useState("home"),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[form,setForm]=useState<any>(null),[pending,setPending]=useState<any>(null);
 const dataRef=useRef<State|null>(null);
 async function load(){setLoading(true);try{const r=await fetch("/api/kho",{cache:"no-store"});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);setData(d);dataRef.current=d;setError("");setForm((f:any)=>f??newVoucher("RECEIPT",d.revision,d.user));return d;}catch(e:any){setError(e.message);throw e;}finally{setLoading(false);}}
 useEffect(()=>{load().catch(()=>{});},[]);
 useEffect(()=>{const check=(e:BeforeUnloadEvent)=>{if(form?.lines?.some((l:any)=>l.item||l.quantity)){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",check);return()=>window.removeEventListener("beforeunload",check);},[form]);
 async function execute(action:string,payload:any,extra:any={}){
  if(busy)throw new Error("Một thao tác đang được xử lý.");setBusy(true);
  try{const res=await fetch("/api/kho",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,payload,revision:dataRef.current?.revision,id:extra.id??crypto.randomUUID(),...extra})});const out=await res.json() as any;if(!res.ok)throw new Error(out.error);
  try{await load();}catch{toast.warning("Đã ghi thành công. Cần tải lại để cập nhật báo cáo.");}
  toast.success(action==="draft"?"Đã lưu phiếu nháp":action==="transaction"?"Đã ghi phiếu "+out.number:action==="item"?(out.countRef||out.countNumber?`Đã lưu mặt hàng ${out.code} (Kiểm kê: ${out.countRef||out.countNumber})`:`Đã lưu mặt hàng ${out.code}`):"Đã lưu thay đổi");return out;
  }finally{setBusy(false);}
 }
 function applyNew(next:any){setForm(next);setTab(next.type==="COUNT"?"count":"voucher");}
 function start(type:TxType,extra:any={}){
  if(!data)return;const next={...newVoucher(type,data.revision,data.user),...extra};
  if(form?.lines?.some((l:any)=>l.item||l.quantity))setPending(next);else applyNew(next);
 }
 function go(t:string){if(t==="count"){if(form?.type==="COUNT")setTab(t);else start("COUNT");}else setTab(t);}
 function fromStock(r:any,type:TxType){start(type,{from:r.location,to:type==="COUNT"?r.location:r.location==="KHO_TONG"?"BUONG_PHONG":"KHO_TONG",lines:[{item:r.item,quantity:"",price:"",unitMode:"base",lot:r.lot,expiry:r.expiry,condition:r.condition}]});}
 useEffect(()=>{
  const mc=(document as any).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();
  const tools=[{name:"search_inventory",title:"Tra cứu tồn kho",description:"Read inventory already visible to the signed-in warehouse manager. Returns up to 25 matching rows without changing stock.",inputSchema:{type:"object",properties:{query:{type:"string"},location:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.query!=="string"||input.query.length>200)throw new Error("Invalid query");const d=dataRef.current;if(!d)throw new Error("Inventory has not loaded");const location=input.location??"KHO_TONG";if(!d.locations.some(l=>l.id===location))throw new Error("Unknown location");return stockRows(d,location).filter(r=>normalize(r.itemData.name+" "+r.item).includes(normalize(input.query))).slice(0,25).map(r=>({code:r.item,name:r.itemData.name,location,recordedQuantity:r.quantity/1000,unit:r.itemData.unit,verified:!!r.verified_at,lot:r.lot,expiry:r.expiry}));}}];
  for(const tool of tools)Promise.resolve(mc.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});
  return()=>lifecycle.abort();
 },[]);
 return <SidebarProvider><Sidebar><SidebarHeader className="p-6 pb-4"><div className="flex gap-3 items-center"><div className="rounded-xl p-2 bg-[#c9ef8e] text-[#123b3f]"><Package size={27}/></div><div><div className="text-2xl font-bold tracking-wide">LAKA<span className="font-normal text-lg ml-1">Kho</span></div><p className="text-xs text-[#b2cccd]">QUẢN LÝ & CẤP PHÁT</p></div></div></SidebarHeader><SidebarContent><SidebarGroup className="px-3"><Navigation tab={tab} go={go}/></SidebarGroup><div className="mx-5 mt-auto mb-5 p-4 rounded-xl border border-[#37666a] bg-[#1a4549]"><ShieldCheck size={20} className="text-[#c9ef8e] mb-2"/><b className="text-sm">Không gian riêng tư</b><p className="text-xs text-[#bed3d4] mt-1">Dữ liệu kho dành cho người quản lý.</p></div></SidebarContent><SidebarFooter className="border-t border-sidebar-border p-4"><span className="text-sm truncate">{data?.user??"Người quản lý kho"}</span><form action="/api/auth/logout" method="post"><button type="submit" className="text-xs flex gap-2 items-center text-[#bed3d4]"><LogOut size={13}/> Đăng xuất</button></form></SidebarFooter></Sidebar>
 <SidebarInset><header className="h-[72px] bg-card border-b px-4 md:px-8 flex items-center justify-between gap-4 no-print"><div className="flex items-center gap-3"><SidebarTrigger/><span className="text-sm text-muted-foreground">Vận hành <span className="mx-2">/</span> <b className="text-foreground">{navigation.find(n=>n[0]===tab)?.[1]}</b></span></div><div className="flex gap-2"><Button variant="ghost" size="icon" aria-label="Tải lại dữ liệu" disabled={loading||busy} onClick={()=>load().catch(()=>{})}><RefreshCw size={18} className={loading?"animate-spin":""}/></Button><Button onClick={()=>start("RECEIPT")} disabled={!data||busy}><Plus size={18}/><span className="desktop-label">Lập phiếu</span></Button></div></header>
 <main className="app-main">{error&&<div className="bg-red-50 text-red-800 border border-red-200 rounded-xl p-4 mb-5" role="alert">{error} <Button variant="outline" size="sm" onClick={()=>load().catch(()=>{})}>Thử tải lại</Button></div>}{!data?(!error&&<Empty title="Đang tải kho…" detail="Đang đọc danh mục và các phiếu đã ghi."/>):<>
 {tab==="home"&&<Overview data={data} start={start} go={go}/>}
 {(tab==="voucher"||tab==="count")&&form&&<VoucherForm data={data} form={form} setForm={setForm} execute={execute} busy={busy} onDone={()=>{setForm(newVoucher("RECEIPT",dataRef.current?.revision??0,data.user));setTab("history");}}/>}
 {tab==="stock"&&<InventoryView data={data} onCount={(r:any)=>fromStock(r,"COUNT")} onTransfer={(r:any)=>fromStock(r,"TRANSFER")}/>}
 {tab==="catalog"&&<CatalogView data={data} execute={execute} busy={busy}/>}
 {tab==="suppliers"&&<SuppliersView data={data} execute={execute} busy={busy}/>}
 {tab==="purchases"&&<PurchasesView data={data} execute={execute} busy={busy}/>}
 {tab==="settings"&&<SettingsView data={data} execute={execute} busy={busy}/>}
 {tab==="analytics"&&<AnalyticsView data={data} go={go}/>}
 {tab==="history"&&<HistoryView data={data} execute={execute} busy={busy} openDraft={(draft:any)=>{if(form?.lines?.some((l:any)=>l.item||l.quantity))setPending(draft);else applyNew(draft);}}/>}
 {tab==="data"&&<DataView data={data}/>}</>}</main>
 <footer className="mt-auto px-8 py-4 text-xs text-muted-foreground border-t flex flex-wrap justify-between gap-2 no-print"><span>LAKA Kho · Sổ vận hành</span><span>Ngày làm việc: {dt(today())} · Giờ Việt Nam</span></footer></SidebarInset><Toaster richColors position="top-right" theme="light"/>
 <AlertDialog open={!!pending} onOpenChange={v=>!v&&setPending(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Bạn có phiếu đang soạn</AlertDialogTitle><AlertDialogDescription>Lưu nháp để giữ nội dung trước khi chuyển sang phiếu khác.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter className="flex-wrap"><AlertDialogCancel disabled={busy}>Ở lại phiếu này</AlertDialogCancel><Button variant="outline" disabled={busy} onClick={()=>{applyNew(pending);setPending(null);}}>Bỏ nội dung đang soạn</Button><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();try{await execute("draft",form,{id:form.id});applyNew(pending);setPending(null);}catch(e:any){toast.error(e.message);}}}>Lưu nháp & tiếp tục</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></SidebarProvider>;
}
function Overview({data,start,go}:{data:State;start:any;go:any}){
 const current=today(),tx=data.transactions.filter(t=>t.date===current),todayCount=data.todayTxCount??tx.length,unclassified=data.items.filter(i=>i.active&&i.kind==="unclassified").length,verified=new Set(data.balances.filter(b=>b.verified_at).map(b=>b.item)).size;
 const warnings=data.locations.flatMap(l=>stockRows(data,l.id)).filter(r=>r.low),low=new Set(warnings.map(r=>r.location+r.item)).size;
 const expiring=data.balances.filter(b=>b.quantity>0&&b.expiry&&b.expiry<=new Date(Date.now()+30*86400000).toISOString().slice(0,10));
 return <><Heading title="Kho hôm nay" detail={new Date().toLocaleDateString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh",weekday:"long",day:"numeric",month:"long",year:"numeric"})}><span className="pill good">Dữ liệu đã tải</span></Heading>
 <div className="grid sm:grid-cols-3 gap-3 mb-7">{[[ArrowDownToLine,"Nhập hàng","Nhận tại kho hoặc giao thẳng khu","RECEIPT"],[ArrowRightLeft,"Cấp hàng cho khu","Bàn giao nhiều món trong một phiếu","TRANSFER"],[ClipboardCheck,"Kiểm kê thực tế","Xác nhận số dư và chênh lệch","COUNT"]].map(([Icon,title,detail,type]:any)=><button className="action-card" key={type} onClick={()=>start(type)}><Icon size={27} className="shrink-0"/><span><b>{title}</b><small className="subtle block mt-1">{detail}</small></span></button>)}</div>
 <section className="panel grid grid-cols-2 xl:grid-cols-4 gap-6 mb-7">{[["Mặt hàng đang dùng",data.items.filter(i=>i.active).length,"Danh mục chung"],["Phiếu hôm nay",todayCount,"Theo ngày thực tế (chuẩn máy chủ)"],["Cần bổ sung",low,"Mặt hàng / khu có định mức"],["Lô cần xem hạn",expiring.length,"Đã hết hạn hoặc còn ≤ 30 ngày"]].map(([label,value,note])=><div className="metric cursor-pointer" key={String(label)} onClick={()=>String(label)==="Phiếu hôm nay"?go("analytics"):undefined}><span className="text-sm font-medium">{label}</span><strong>{value}</strong><span className="subtle text-xs">{note}</span></div>)}</section>
 {(unclassified>0||verified===0)&&<section className="mb-7 rounded-2xl bg-[#123b3f] text-white p-6 md:p-8"><div className="grid lg:grid-cols-[1fr_340px] gap-6"><div><span className="eyebrow text-[#c9ef8e]">Chuẩn bị vận hành</span><h2 className="text-2xl font-semibold mt-2 mb-3">{verified===0?"Bắt đầu bằng một khu, một lần kiểm kê":"Hoàn thiện danh mục quản lý"}</h2><p className="text-sm text-[#c9dede] max-w-xl leading-6">Danh mục từ file nguồn đã có sẵn. Xác nhận loại hàng và số lượng thực đếm để các phiếu nhập, cấp phát và cảnh báo đi đúng từ đầu.</p></div><div className="space-y-2"><button className="w-full flex items-center justify-between gap-3 text-left p-3 rounded-lg bg-[#215357]" onClick={()=>go("catalog")}><span className="text-sm">Phân loại hàng <b className="block text-[#c9ef8e]">{unclassified} mã cần kiểm tra</b></span><ChevronRight size={18}/></button><button className="w-full flex items-center justify-between gap-3 text-left p-3 rounded-lg bg-[#215357]" onClick={()=>start("COUNT")}><span className="text-sm">Kiểm kê số dư đầu <b className="block text-[#c9ef8e]">{verified} mặt hàng đã xác nhận tại ít nhất một khu</b></span><ChevronRight size={18}/></button></div></div></section>}
 <div className="grid xl:grid-cols-[1.2fr_1fr] gap-6"><section className="panel"><div className="flex justify-between items-center gap-3 mb-4"><h2 className="text-xl font-semibold">Phiếu gần đây</h2><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>go("analytics")}><TrendingUp size={16}/> Luồng hàng</Button><Button variant="ghost" size="sm" onClick={()=>go("history")}>Xem tất cả <ArrowUpRight size={16}/></Button></div></div>{!data.transactions.length?<Empty title="Chưa có phiếu vận hành" detail="Lịch sử mua cũ được giữ ở mục Dữ liệu & báo cáo."/>:<div className="divide-y">{data.transactions.slice(0,6).map(t=><button className="w-full flex justify-between text-left items-center gap-3 py-4" key={t.id} onClick={()=>go("history")}><span><b className="text-sm">{TYPES[t.type as TxType]}</b><small className="subtle block">{t.number} · {dt(t.date)}</small></span><span className="text-right text-sm">{t.lines.length} dòng<small className="subtle block">{data.locations.find(l=>l.id===(t.to_location||t.from_location))?.name}</small></span></button>)}</div>}{data.drafts.length>0&&<Button variant="outline" className="w-full mt-4" onClick={()=>go("history")}>{data.drafts.length} phiếu đang soạn</Button>}</section>
 <section className="panel"><div className="flex justify-between items-center gap-3 mb-4"><h2 className="text-xl font-semibold">Các khu quản lý</h2><Button variant="ghost" size="sm" onClick={()=>go("settings")}>Thiết lập</Button></div><div className="divide-y">{data.locations.filter(l=>l.active).map(l=>{const count=new Set(data.balances.filter(b=>b.location===l.id&&b.verified_at).map(b=>b.item)).size;return <div className="py-3 flex items-center justify-between gap-3" key={l.id}><span className="text-sm font-medium">{l.name}</span><span className={"pill "+(count?"good":"warn")}>{count?count+" mã đã kiểm kê":"Chưa kiểm kê"}</span></div>;})}</div></section></div>
 <p className="subtle mt-5 flex items-start gap-2"><ShieldCheck size={17} className="shrink-0 mt-0.5"/>Lịch sử mua cũ không tự cộng vào tồn. Hàng chưa kiểm kê luôn được đánh dấu để đối soát.</p></>;
}
