"use client";
import {useEffect,useState} from "react";
import {Plus,Printer,Download,Trash2,Wallet,Link2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from "@/components/ui/dialog";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Field,Pick,ItemPicker,SearchBox,Heading,Empty,money,qty,dt,csv,download} from "./kho-ui";
import {today,normalize,type State} from "@/lib/inventory";
import {billStatus,supplierTotals,prepareInvoice,prepareSupplier,PAYMENT_STATUS,METHODS,type Invoice,type Supplier} from "@/lib/commerce";
import {ChoiceField,MultiChoiceField,NoteField} from "./choice-fields";
import {CATEGORIES,UNITS,BANKS,TERMS,mergeOptions,splitCategories} from "@/lib/form-options";
type Props={data:State;execute:any;busy:boolean};
function useLeaveWarning(dirty:boolean){useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};if(dirty)window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);}
function ErrorText({error}:{error:string}){return error?<p role="alert" className="p-3 bg-red-50 text-red-800 rounded-lg">{error}</p>:null;}
function PaymentBadge({bill}:{bill:Invoice}){const s=billStatus(bill);return <div><span className={"pill "+(s.status==="paid"?"good":s.status==="void"?"":"warn")}>{PAYMENT_STATUS[s.status]}</span>{s.overdue&&<span className="pill bad ml-1">Quá hạn</span>}</div>;}
export function SuppliersView({data,execute,busy}:Props){
 const [search,setSearch]=useState(""),[form,setForm]=useState<any>(null),[requestId,setRequestId]=useState(""),[error,setError]=useState("");
 const totals=supplierTotals(data.invoices),rows=data.suppliers.filter(s=>normalize([s.code,s.name,s.contact,s.phone,s.categories].join(" ")).includes(normalize(search)));
 useLeaveWarning(!!form);
 function edit(s?:Supplier){setForm(s?{...s,autoCode:false}:{id:crypto.randomUUID(),autoCode:true,code:"",name:"",contact:"",phone:"",email:"",address:"",tax_id:"",bank_name:"",bank_account:"",bank_holder:"",categories:"",terms_days:0,note:"",active:1});setRequestId(crypto.randomUUID());setError("");}
 async function save(){try{prepareSupplier({...form,code:form.autoCode?"NCC-AUTO":form.code,terms_days:Number(form.terms_days)});await execute("supplier",{...form,code:form.autoCode?"":form.code,terms_days:Number(form.terms_days)},{id:requestId});setForm(null);}catch(e:any){setError(e.message);}}
 return <><Heading title="Nhà cung cấp" detail="Lưu thông tin liên hệ, thanh toán và công nợ của từng nhà cung cấp."><Button onClick={()=>edit()}><Plus/> Thêm NCC</Button></Heading><SearchBox value={search} onChange={setSearch} placeholder="Tìm tên, mã, điện thoại hoặc nhóm hàng…"/>
 <div className="panel p-0 overflow-hidden mt-4"><Table><TableHeader><TableRow><TableHead>Nhà cung cấp</TableHead><TableHead>Liên hệ</TableHead><TableHead>Nhóm hàng</TableHead><TableHead>Còn nợ</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.map(s=>{const total=totals.find(t=>t.supplier_id===s.id);return <TableRow key={s.id}><TableCell className="table-cell-name"><b>{s.name}</b><p className="subtle">{s.code}{!s.active?" · Ngừng giao dịch mới":""}</p></TableCell><TableCell>{s.contact||"—"}<p className="subtle">{s.phone}</p></TableCell><TableCell className="whitespace-normal">{s.categories||"—"}</TableCell><TableCell>{money(total?.outstanding??0)}{!!total?.overdue&&<p className="text-red-700 text-sm">Quá hạn: {money(total.overdue)}</p>}</TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>edit(s)}>Chi tiết / sửa</Button></TableCell></TableRow>;})}</TableBody></Table>{!rows.length&&<Empty title="Chưa có nhà cung cấp phù hợp" detail="Tên và số liên hệ có thể nhập trước, thông tin khác bổ sung sau."/>}</div>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy&&window.confirm("Đóng hồ sơ đang sửa? Thay đổi chưa lưu sẽ bị bỏ."))setForm(null);}}><DialogContent className="sm:max-w-3xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Thông tin nhà cung cấp</DialogTitle><DialogDescription>Mã số thuế và tài khoản ngân hàng không bắt buộc.</DialogDescription></DialogHeader>{form&&<><div className="grid sm:grid-cols-2 gap-4">{[["code","Mã NCC *"],["name","Tên NCC / cửa hàng *"],["contact","Người liên hệ"],["phone","Điện thoại / Zalo"],["email","Email"],["categories","Nhóm hàng cung cấp"],["address","Địa chỉ"],["tax_id","Mã số thuế (nếu có)"],["bank_name","Ngân hàng"],["bank_account","Số tài khoản"],["bank_holder","Chủ tài khoản"]].map(([key,label])=><Field key={key} label={label}>{key==="code"?<div className="space-y-1">{form.autoCode?<p className="rounded-md border p-3 text-sm">Tự cấp mã NCC khi lưu</p>:<Input value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/>}<Button type="button" variant="ghost" size="sm" onClick={()=>setForm({...form,autoCode:!form.autoCode})}>{form.autoCode?"Nhập mã riêng":"Dùng mã tự động"}</Button></div>:key==="categories"?<MultiChoiceField label={label} value={form[key]} onChange={v=>setForm({...form,[key]:v})} options={mergeOptions(CATEGORIES,data.items.map(i=>i.category),data.suppliers.flatMap(i=>splitCategories(i.categories)))}/>:key==="bank_name"?<ChoiceField label={label} value={form[key]} onChange={v=>setForm({...form,[key]:v})} options={mergeOptions(data.suppliers.map(i=>i.bank_name),BANKS)}/>:key==="contact"||key==="bank_holder"?<ChoiceField label={label} value={form[key]} onChange={v=>setForm({...form,[key]:v})} options={mergeOptions(data.suppliers.map(i=>i[key as "contact"|"bank_holder"]))} maxLength={200}/>:<Input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</Field>)}<Field label="Hạn thanh toán mặc định (ngày)"><ChoiceField label="Số ngày được nợ (0 = thanh toán ngay)" value={String(form.terms_days)} onChange={v=>setForm({...form,terms_days:v})} options={mergeOptions(TERMS,data.suppliers.map(s=>String(s.terms_days)))} maxLength={4}/></Field><Field label="Trạng thái"><Pick label="Trạng thái NCC" value={String(form.active)} onChange={v=>setForm({...form,active:Number(v)})} options={[{value:"1",label:"Đang giao dịch"},{value:"0",label:"Ngừng giao dịch mới"}]}/></Field></div><Field label="Ghi chú / điều khoản giao hàng"><NoteField kind="supplier" value={form.note} onChange={v=>setForm({...form,note:v})}/></Field><ErrorText error={error}/><DialogFooter><Button disabled={busy} onClick={save}>{busy?"Đang lưu…":"Lưu nhà cung cấp"}</Button></DialogFooter></>}</DialogContent></Dialog></>;
}
const emptyLine=()=>({item:"",name:"",unit:"",quantity:"",price:""});
function blankInvoice(){return {id:crypto.randomUUID(),supplier_id:"",date:today(),due_date:"",reference:"",buyer_name:"LAKA Homestay",buyer_address:"",lines:[emptyLine()],discount:"0",shipping:"0",note:"",receipt_ids:[] as string[]};}
function termsDate(date:string,days:number){const d=new Date(date+"T00:00:00Z");if(Number.isNaN(+d))return "";d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function InvoiceForm({data,execute,busy,close}:Props&{close:()=>void}){
 const [form,setForm]=useState<any>(blankInvoice),[review,setReview]=useState<any>(null),[error,setError]=useState("");useLeaveWarning(true);
 const set=(key:string,value:any)=>setForm({...form,[key]:value});
 const receipts=availableReceipts(data);
 function fromReceipt(id:string){const t=receipts.find(r=>r.id===id);if(!t)return;const supplier=data.suppliers.find(s=>s.active&&normalize(s.name)===normalize(t.partner));setForm({...form,supplier_id:supplier?.id??form.supplier_id,due_date:supplier?termsDate(form.date,supplier.terms_days):form.due_date,receipt_ids:[id],lines:t.lines.map((l:any)=>({item:l.item,name:l.itemName,unit:l.enteredUnit||l.baseUnit,quantity:String(l.quantity),price:l.priceMissing?"":String(l.price)}))});}
 function preview(){try{const payload={...form,lines:form.lines.map((l:any)=>({...l,quantity:l.quantity===""?NaN:Number(l.quantity),price:l.price===""?NaN:Number(l.price)})),discount:Number(form.discount),shipping:Number(form.shipping)};const prepared=prepareInvoice(payload);if(!data.suppliers.some(s=>s.id===payload.supplier_id&&s.active))throw new Error("Chọn NCC đang hoạt động.");setReview({payload,...prepared});setError("");}catch(e:any){setError(e.message);}}
 async function save(){try{await execute("invoice",review.payload,{id:form.id});close();}catch(e:any){setError(e.message);}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy&&window.confirm("Bỏ chứng từ chưa ghi?"))close();}}><DialogContent className="sm:max-w-5xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>{review?"Xác nhận chứng từ mua":"Lập chứng từ mua hàng"}</DialogTitle><DialogDescription>Ghi tiền phải trả NCC. Tồn kho chỉ thay đổi khi lập phiếu nhập hàng.</DialogDescription></DialogHeader>{review?<><p><b>NCC:</b> {data.suppliers.find(s=>s.id===review.supplier_id)?.name}</p><p>Ngày: {dt(review.date)} · Hạn thanh toán: {dt(review.due_date)}</p><BillLines lines={review.lines}/><p className="text-right">Tiền hàng: {money(review.subtotal)} · Giảm: {money(review.discount)} · Phí: {money(review.shipping)}</p><p className="text-right text-xl font-bold">Phải trả: {money(review.total)}</p><p className="subtle">Sau khi ghi, chứng từ được giữ nguyên. Nếu sai, hủy chứng từ và lập lại. Ghi khoản đặt cọc hoặc thanh toán sau khi tạo chứng từ.</p><ErrorText error={error}/><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setReview(null)}>Quay lại sửa</Button><Button disabled={busy} onClick={save}>Xác nhận ghi chứng từ</Button></DialogFooter></>:<>
 <div className="grid sm:grid-cols-2 gap-4"><Field label="Nhà cung cấp *" hint="Chưa có NCC? Tạo hồ sơ tại mục Nhà cung cấp trước."><Pick label="Nhà cung cấp" value={form.supplier_id} onChange={v=>{const s=data.suppliers.find(x=>x.id===v)!;setForm({...form,supplier_id:v,due_date:termsDate(form.date,s.terms_days)});}} options={data.suppliers.filter(s=>s.active).map(s=>({value:s.id,label:s.name+" · "+s.code}))}/></Field><Field label="Lấy hàng từ phiếu nhập (tùy chọn)"><Pick label="Phiếu nhập có sẵn" value={form.receipt_ids[0]??""} onChange={fromReceipt} options={receipts.map(t=>({value:t.id,label:t.number+" · "+t.partner}))}/></Field><Field label="Ngày chứng từ *"><Input type="date" max={today()} value={form.date} onChange={e=>{const date=e.target.value,supplier=data.suppliers.find(s=>s.id===form.supplier_id),automatic=supplier&&form.due_date===termsDate(form.date,supplier.terms_days);setForm({...form,date,due_date:automatic?termsDate(date,supplier.terms_days):form.due_date});}}/></Field><Field label="Hạn thanh toán (để trống nếu chưa hẹn)"><Input type="date" min={form.date} value={form.due_date} onChange={e=>set("due_date",e.target.value)}/></Field><Field label="Số chứng từ NCC (nếu có)"><Input value={form.reference} onChange={e=>set("reference",e.target.value)}/></Field><Field label="Tên bên mua *"><ChoiceField label="Tên bên mua" value={form.buyer_name} onChange={v=>{const addresses=mergeOptions(data.invoices.filter(i=>i.buyer_name===v).map(i=>i.buyer_address));setForm({...form,buyer_name:v,buyer_address:addresses.length===1?addresses[0]:""});}} options={mergeOptions(["LAKA Homestay"],data.invoices.map(i=>i.buyer_name))} maxLength={200}/></Field><Field label="Địa chỉ bên mua"><ChoiceField label="Địa chỉ bên mua" value={form.buyer_address} onChange={v=>set("buyer_address",v)} options={mergeOptions(data.invoices.filter(i=>i.buyer_name===form.buyer_name).map(i=>i.buyer_address))} maxLength={500}/></Field></div>
 {!!form.receipt_ids.length&&<p className="subtle">Đã chọn phiếu nhập để đối chiếu. Kiểm tra NCC và các dòng trước khi ghi. <Button size="sm" variant="ghost" onClick={()=>set("receipt_ids",[])}>Bỏ liên kết</Button></p>}
 {form.lines.map((line:any,index:number)=><section className="line-card space-y-3" key={index}><div className="flex gap-2 items-center"><b>Dòng {index+1}</b><Button aria-label={"Bỏ dòng "+(index+1)} variant="ghost" size="icon" disabled={form.lines.length===1} onClick={()=>set("lines",form.lines.filter((_:any,j:number)=>j!==index))}><Trash2 size={16}/></Button></div><Field label="Chọn hàng trong danh mục (tùy chọn)"><ItemPicker items={data.items} value={line.item} onChange={v=>{const item=data.items.find(i=>i.code===v);set("lines",form.lines.map((l:any,j:number)=>j===index?{...l,item:v,name:item?.name??l.name,unit:item?.unit??l.unit}:l));}}/></Field><div className="grid sm:grid-cols-[2fr_1fr_1fr_1fr] gap-3">{[["name","Tên hàng *"],["unit","Đơn vị *"],["quantity","Số lượng *"],["price","Đơn giá VND *"]].map(([key,label])=><Field key={key} label={label}>{key==="unit"?<ChoiceField label="Đơn vị trên chứng từ" value={line.unit} onChange={v=>set("lines",form.lines.map((l:any,j:number)=>j===index?{...l,unit:v}:l))} options={mergeOptions(data.items.flatMap(i=>[i.unit,i.pack_unit]),UNITS)} maxLength={40}/>:<Input type={key==="quantity"||key==="price"?"number":"text"} min="0" step={key==="quantity"?"0.001":"1"} value={line[key]} onChange={e=>set("lines",form.lines.map((l:any,j:number)=>j===index?{...l,[key]:e.target.value}:l))}/> }</Field>)}</div></section>)}
 <Button variant="outline" disabled={form.lines.length>=100} onClick={()=>set("lines",[...form.lines,emptyLine()])}><Plus/> Thêm dòng hàng</Button><div className="grid sm:grid-cols-2 gap-4"><Field label="Giảm giá toàn chứng từ (VND)"><Input type="number" min="0" step="1" value={form.discount} onChange={e=>set("discount",e.target.value)}/></Field><Field label="Vận chuyển / chi phí thêm (VND)"><Input type="number" min="0" step="1" value={form.shipping} onChange={e=>set("shipping",e.target.value)}/></Field></div><Field label="Ghi chú"><NoteField kind="invoice" value={form.note} onChange={v=>set("note",v)}/></Field><ErrorText error={error}/><DialogFooter><Button disabled={busy} onClick={preview}>Xem lại & xác nhận</Button></DialogFooter></>}</DialogContent></Dialog>;
}
function availableReceipts(data:State){const linked=new Set(data.receiptLinks.filter(r=>data.invoices.some(b=>b.id===r.invoice_id&&!b.void_id)).map(r=>r.tx_id)),reversed=new Set(data.transactions.filter(t=>t.reversal_of).map(t=>t.reversal_of));return data.transactions.filter(t=>t.type==="RECEIPT"&&!reversed.has(t.id)&&!linked.has(t.id));}
function BillLines({lines}:{lines:any[]}){return <Table><TableHeader><TableRow><TableHead>Hàng hóa</TableHead><TableHead>SL / ĐVT</TableHead><TableHead>Đơn giá</TableHead><TableHead>Thành tiền</TableHead></TableRow></TableHeader><TableBody>{lines.map((l,i)=><TableRow key={i}><TableCell className="table-cell-name">{l.name}{l.item&&<p className="subtle">{l.item}</p>}</TableCell><TableCell>{qty(l.quantity)} {l.unit}</TableCell><TableCell>{money(l.price)}</TableCell><TableCell>{money(l.amount)}</TableCell></TableRow>)}</TableBody></Table>;}
export function PurchasesView({data,execute,busy}:Props){
 const [search,setSearch]=useState(""),[supplier,setSupplier]=useState("all"),[status,setStatus]=useState("all"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[page,setPage]=useState(0),[create,setCreate]=useState(false),[selectedId,setSelectedId]=useState(""),[action,setAction]=useState<any>(null),[error,setError]=useState("");
 const selected=data.invoices.find(i=>i.id===selectedId),all=data.invoices.filter(b=>{const s=billStatus(b);return (supplier==="all"||b.supplier_id===supplier)&&(!from||b.date>=from)&&(!to||b.date<=to)&&(status==="all"||status==="debt"&&s.outstanding>0||status==="overdue"&&s.overdue||status===s.status)&&normalize(b.number+" "+b.reference+" "+b.supplier_snapshot.name).includes(normalize(search));});
 const summary=supplierTotals(all),totals=summary.reduce((a,r)=>({total:a.total+r.total,paid:a.paid+r.paid,outstanding:a.outstanding+r.outstanding,overdue:a.overdue+r.overdue}),{total:0,paid:0,outstanding:0,overdue:0});
 useLeaveWarning(!!action);useEffect(()=>setPage(0),[search,supplier,status,from,to]);
 function startAction(kind:string,bill:Invoice,paymentId?:string){setError("");setAction({kind,id:crypto.randomUUID(),invoice_id:bill.id,payment_id:paymentId,date:today(),amount:String(billStatus(bill).outstanding),method:"cash",reference:"",note:"",reason:"",tx_id:""});}
 async function submitAction(){try{const {id,kind,...payload}=action;await execute(kind,{...payload,amount:Number(payload.amount)},{id});setAction(null);setError("");}catch(e:any){setError(e.message);}}
 function exportBills(){download("chung-tu-cong-no-"+today()+".csv",csv([["Số chứng từ","NCC","Ngày","Hạn thanh toán","Tham chiếu NCC","Tổng tiền","Đã trả ròng","Còn nợ","Trạng thái","Quá hạn","Lý do hủy"],...all.map(b=>{const s=billStatus(b);return [b.number,b.supplier_snapshot.name,b.date,b.due_date,b.reference,b.total,b.paid,s.outstanding,PAYMENT_STATUS[s.status],s.overdue?"Có":"",b.void_reason];})]),"text/csv;charset=utf-8");}
 function exportPayments(){const bills=new Map(data.invoices.map(b=>[b.id,b]));const rows=data.payments.filter(p=>(!from||p.date>=from)&&(!to||p.date<=to)&&(supplier==="all"||bills.get(p.invoice_id)?.supplier_id===supplier));download("lich-su-tra-ncc-"+today()+".csv",csv([["Mã lần trả","Chứng từ","NCC","Ngày trả / đảo","Số tiền tăng / giảm","Phương thức","Tham chiếu","Đảo lần trả","Ghi chú"],...rows.map(p=>{const b=bills.get(p.invoice_id)!;return [p.id,b.number,b.supplier_snapshot.name,p.date,p.amount,METHODS[p.method as keyof typeof METHODS],p.reference,p.reversal_of,p.note];})]),"text/csv;charset=utf-8");}
 return <><Heading title="Mua hàng & công nợ" detail="Chứng từ mua nội bộ, lịch sử trả tiền và khoản còn nợ nhà cung cấp."><Button onClick={()=>setCreate(true)}><Plus/> Lập chứng từ mua</Button></Heading>
 <section className="panel grid sm:grid-cols-2 xl:grid-cols-4 gap-5 mb-5">{[["Tiền mua",totals.total],["Đã trả ròng",totals.paid],["Còn nợ",totals.outstanding],["Nợ quá hạn",totals.overdue]].map(([label,value])=><div key={String(label)}><p className="subtle">{label}</p><b className="text-xl">{money(Number(value))}</b></div>)}</section>
 <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3 mb-4"><SearchBox value={search} onChange={setSearch} placeholder="Tìm số chứng từ hoặc tên NCC…"/><Pick label="Lọc NCC" value={supplier} onChange={setSupplier} options={[{value:"all",label:"Tất cả NCC"},...data.suppliers.map(s=>({value:s.id,label:s.name}))]}/><Pick label="Lọc thanh toán" value={status} onChange={setStatus} options={[{value:"all",label:"Tất cả trạng thái"},{value:"debt",label:"Còn nợ"},{value:"overdue",label:"Nợ quá hạn"},...Object.entries(PAYMENT_STATUS).map(([value,label])=>({value,label}))]}/><Field label="Từ ngày"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Đến ngày"><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field></div>
 <p className="subtle mb-4">Số tổng theo chứng từ trong bộ lọc, trạng thái thanh toán hiện tại; không phải số dư chốt tại ngày quá khứ. Chứng từ đã hủy không cộng vào tổng.</p><div className="flex flex-wrap gap-2 mb-4"><Button variant="outline" onClick={exportBills}><Download/> Xuất chứng từ / công nợ CSV</Button><Button variant="outline" onClick={exportPayments}><Download/> Xuất lịch sử trả tiền CSV</Button></div><p className="subtle mb-4">Lịch sử trả tiền lọc theo ngày trả/đảo và NCC; không áp dụng ô tìm kiếm hoặc trạng thái chứng từ.</p>
 <div className="panel p-0 overflow-hidden"><Table><TableHeader><TableRow><TableHead>Chứng từ / NCC</TableHead><TableHead>Ngày / hạn trả</TableHead><TableHead>Phải trả</TableHead><TableHead>Đã trả</TableHead><TableHead>Còn nợ</TableHead><TableHead>Trạng thái</TableHead><TableHead/></TableRow></TableHeader><TableBody>{all.slice(page*25,page*25+25).map(b=><TableRow key={b.id}><TableCell className="table-cell-name"><b>{b.number}</b><p className="subtle">{b.supplier_snapshot.name}</p></TableCell><TableCell>{dt(b.date)}<p className="subtle">Hạn: {dt(b.due_date)}</p></TableCell><TableCell>{money(b.total)}</TableCell><TableCell>{money(b.paid)}</TableCell><TableCell>{money(billStatus(b).outstanding)}</TableCell><TableCell><PaymentBadge bill={b}/></TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>{setSelectedId(b.id);setError("");}}>Mở</Button></TableCell></TableRow>)}</TableBody></Table>{!all.length&&<Empty title="Chưa có chứng từ phù hợp" detail="Tạo NCC, lập chứng từ mua, rồi ghi từng lần thanh toán."/>}<div className="p-4 flex justify-between"><span className="subtle">{all.length} chứng từ</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>Trước</Button><Button size="sm" variant="outline" disabled={(page+1)*25>=all.length} onClick={()=>setPage(page+1)}>Sau</Button></div></div></div>
 <section className="panel mt-5"><h2 className="text-lg font-semibold mb-3">Tổng hợp theo nhà cung cấp</h2><Table><TableHeader><TableRow><TableHead>NCC</TableHead><TableHead>Số chứng từ</TableHead><TableHead>Tiền mua</TableHead><TableHead>Đã trả</TableHead><TableHead>Còn nợ</TableHead><TableHead>Quá hạn</TableHead></TableRow></TableHeader><TableBody>{summary.map(r=><TableRow key={r.supplier_id}><TableCell>{data.suppliers.find(s=>s.id===r.supplier_id)?.name}</TableCell><TableCell>{r.count}</TableCell><TableCell>{money(r.total)}</TableCell><TableCell>{money(r.paid)}</TableCell><TableCell>{money(r.outstanding)}</TableCell><TableCell>{money(r.overdue)}</TableCell></TableRow>)}</TableBody></Table></section>
 {create&&<InvoiceForm data={data} execute={execute} busy={busy} close={()=>setCreate(false)}/>}
 <Dialog open={!!selected&&!action} onOpenChange={v=>!v&&setSelectedId("")}><DialogContent className="sm:max-w-4xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>CHỨNG TỪ MUA HÀNG</DialogTitle><DialogDescription>{selected?.number} · Ngày {dt(selected?.date??"")}</DialogDescription></DialogHeader>{selected&&<><div className="grid sm:grid-cols-2 gap-4 text-sm"><div><b>Bên mua: {selected.buyer_name}</b><p>{selected.buyer_address}</p></div><div><b>Bên bán: {selected.supplier_snapshot.name}</b><p>{selected.supplier_snapshot.address}</p><p>{selected.supplier_snapshot.contact} · {selected.supplier_snapshot.phone}</p>{selected.supplier_snapshot.tax_id&&<p>MST: {selected.supplier_snapshot.tax_id}</p>}<p>{selected.supplier_snapshot.bank_name} {selected.supplier_snapshot.bank_account} {selected.supplier_snapshot.bank_holder}</p></div></div><p className="text-sm">Tham chiếu NCC: {selected.reference||"—"} · Hạn thanh toán: {dt(selected.due_date)}</p><BillLines lines={selected.lines}/><div className="text-right space-y-1"><p>Tiền hàng: {money(selected.subtotal)}</p><p>Giảm giá: {money(selected.discount)} · Phí thêm: {money(selected.shipping)}</p><b className="block text-lg">Tổng phải trả: {money(selected.total)}</b><p>Đã trả ròng: {money(selected.paid)} · Còn nợ: {money(billStatus(selected).outstanding)}</p></div><PaymentBadge bill={selected}/>{selected.void_id&&<p className="text-red-700">Lý do hủy: {selected.void_reason}</p>}<p className="whitespace-pre-wrap text-sm">{selected.note}</p>
 <h3 className="font-semibold mt-3">Các lần thanh toán / điều chỉnh</h3><Table><TableHeader><TableRow><TableHead>Ngày</TableHead><TableHead>Số tiền</TableHead><TableHead>Phương thức / ghi chú</TableHead><TableHead className="no-print"/></TableRow></TableHeader><TableBody>{data.payments.filter(p=>p.invoice_id===selected.id).map(p=><TableRow key={p.id}><TableCell>{dt(p.date)}</TableCell><TableCell>{money(p.amount)}{p.reversal_of&&<p className="subtle">Đảo thanh toán</p>}</TableCell><TableCell className="whitespace-normal">{METHODS[p.method as keyof typeof METHODS]}<p className="subtle">{p.reference} {p.note}</p></TableCell><TableCell className="no-print">{!p.reversal_of&&!data.payments.some(x=>x.reversal_of===p.id)&&!selected.void_id&&<Button variant="ghost" size="sm" onClick={()=>startAction("reversePayment",selected,p.id)}>Đảo lần trả</Button>}</TableCell></TableRow>)}</TableBody></Table>
 <div className="text-sm"><b>Phiếu nhập liên quan:</b>{data.receiptLinks.filter(r=>r.invoice_id===selected.id).map(r=><p key={r.tx_id}>{r.number} · {dt(r.date)} · {r.partner}{!!r.reversed&&<span className="text-red-700"> · Đã đảo phiếu nhập — cần đối soát chứng từ mua</span>}</p>)}{!data.receiptLinks.some(r=>r.invoice_id===selected.id)&&<p className="subtle">Chưa gắn phiếu nhập. Chứng từ này không tự cộng tồn kho.</p>}</div><p className="text-xs">Người lập: {selected.actor}. Chứng từ nội bộ để đối chiếu mua hàng và thanh toán.</p><div className="grid grid-cols-2 gap-8 text-center py-6"><div><b>Người mua / người lập</b><p className="subtle">Ký, ghi rõ họ tên</p></div><div><b>Nhà cung cấp / người nhận tiền</b><p className="subtle">Ký, ghi rõ họ tên</p></div></div>
 <DialogFooter className="no-print flex-wrap"><Button variant="outline" onClick={()=>window.print()}><Printer/> In / Lưu PDF</Button>{!selected.void_id&&<><Button variant="outline" onClick={()=>startAction("linkReceipt",selected)}><Link2/> Gắn phiếu nhập</Button><Button variant="outline" disabled={!!selected.paid} onClick={()=>startAction("voidInvoice",selected)}>Hủy chứng từ</Button>{billStatus(selected).outstanding>0&&<Button onClick={()=>startAction("payment",selected)}><Wallet/> Ghi trả tiền</Button>}</>}</DialogFooter></>}</DialogContent></Dialog>
 <Dialog open={!!action} onOpenChange={v=>!v&&!busy&&setAction(null)}><DialogContent><DialogHeader><DialogTitle>{action?.kind==="payment"?"Ghi nhận trả tiền NCC":action?.kind==="reversePayment"?"Đảo lần thanh toán":action?.kind==="voidInvoice"?"Hủy chứng từ mua":"Gắn phiếu nhập đã nhận"}</DialogTitle><DialogDescription>{selected?.number} · {selected?.supplier_snapshot.name}</DialogDescription></DialogHeader>{action&&<>{action.kind==="linkReceipt"?<><Pick label="Phiếu nhập để gắn" value={action.tx_id} onChange={v=>setAction({...action,tx_id:v})} options={availableReceipts(data).map(t=>({value:t.id,label:t.number+" · "+t.partner}))}/><p className="subtle">Kiểm tra đúng NCC và lô hàng trước khi gắn. Liên kết để tra cứu, không cộng thêm tồn và không xác nhận tự động đã nhận đủ hàng.</p></>:<><Field label="Ngày thực tế"><Input type="date" max={today()} value={action.date} onChange={e=>setAction({...action,date:e.target.value})}/></Field>{action.kind==="payment"&&<><p>Còn nợ: <b>{money(selected?billStatus(selected).outstanding:0)}</b></p><Field label="Số tiền trả (VND) *"><Input type="number" min="1" step="1" value={action.amount} onChange={e=>setAction({...action,amount:e.target.value})}/></Field><Pick label="Phương thức thanh toán" value={action.method} onChange={v=>setAction({...action,method:v})} options={Object.entries(METHODS).map(([value,label])=>({value,label}))}/><Field label="Mã chuyển khoản / phiếu chi"><Input value={action.reference} onChange={e=>setAction({...action,reference:e.target.value})}/></Field></>}<Field label={action.kind==="payment"?"Ghi chú (ví dụ: đặt cọc)":"Lý do *"}><NoteField kind={action.kind} label="Lý do / ghi chú thanh toán" maxLength={1000} value={action.kind==="voidInvoice"?action.reason:action.note} onChange={v=>setAction({...action,[action.kind==="voidInvoice"?"reason":"note"]:v})}/></Field>{action.kind==="reversePayment"&&<p className="subtle">Chỉ dùng khi ghi sai hoặc đã thực nhận lại tiền. Đảo toàn bộ lần trả, giữ lịch sử và tăng lại khoản còn nợ.</p>}{action.kind==="voidInvoice"&&<p className="subtle">Hủy công nợ của chứng từ, giữ lịch sử. Phiếu nhập kho liên quan không bị đảo tự động.</p>}</>}<ErrorText error={error}/><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setAction(null)}>Quay lại</Button><Button disabled={busy} onClick={submitAction}>{busy?"Đang ghi…":"Xác nhận"}</Button></DialogFooter></>}</DialogContent></Dialog></>;
}
