"use client";
import {useState} from "react";
import {Download,FileText,RotateCcw,Printer,ExternalLink,Archive,Database,Search} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from "@/components/ui/table";
import {TYPES,KINDS,normalize,today,type State,type TxType} from "@/lib/inventory";
import {Heading,Field,Pick,SearchBox,Empty,money,qty,dt,download,csv} from "./kho-ui";
import {NoteField} from "./choice-fields";
export function HistoryView({data,execute,busy,openDraft}:{data:State;execute:any;busy:boolean;openDraft:any}){
 const [search,setSearch]=useState(""),[type,setType]=useState("all"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[selected,setSelected]=useState<any>(null),[reverse,setReverse]=useState(false),[reason,setReason]=useState(""),[error,setError]=useState(""),[page,setPage]=useState(0);
 const location=(id:string)=>data.locations.find(l=>l.id===id)?.name??"Bên ngoài";
 const reversed=new Set(data.transactions.map(t=>t.reversal_of).filter(Boolean));
 const list=data.transactions.filter(t=>normalize(t.number+" "+t.partner+" "+t.person+" "+t.note+" "+t.lines.map((l:any)=>l.itemName).join(" ")).includes(normalize(search))&&(type==="all"||type===t.type)&&(!from||t.date>=from)&&(!to||t.date<=to));
 async function confirmReverse(){try{await execute("transaction",{id:crypto.randomUUID(),revision:data.revision,type:"REVERSAL",date:today(),note:reason,reversalOf:selected.id,lines:[]});setReverse(false);setSelected(null);setError("");}catch(e:any){setError(e.message);}}
 return <><Heading title="Phiếu & lịch sử" detail="Tra cứu 500 phiếu gần nhất. Bản xuất dữ liệu chứa toàn bộ lịch sử."/>
 {data.drafts.length>0&&<section className="panel mb-5"><h2 className="font-semibold mb-3">Phiếu đang soạn ({data.drafts.length})</h2><div className="grid sm:grid-cols-2 gap-3">{data.drafts.map(d=><button type="button" className="action-card" key={d.id} onClick={()=>openDraft(d.payload)}><FileText/><span><b>{TYPES[d.payload.type as TxType]??"Phiếu nháp"}</b><small className="subtle block">{d.payload.lines?.length??0} dòng · {dt(d.updated_at)}</small></span></button>)}</div></section>}
 <div className="grid sm:grid-cols-2 xl:grid-cols-[1fr_200px_150px_150px] gap-3 mb-5"><SearchBox value={search} onChange={v=>{setSearch(v);setPage(0);}} placeholder="Tìm số phiếu, hàng, người nhận…"/><Pick label="Loại phiếu trong lịch sử" value={type} onChange={v=>{setType(v);setPage(0);}} options={[{value:"all",label:"Tất cả loại phiếu"},...Object.entries(TYPES).map(([value,label])=>({value,label}))]}/><Input type="date" aria-label="Từ ngày" value={from} onChange={e=>{setFrom(e.target.value);setPage(0);}}/><Input type="date" aria-label="Đến ngày" value={to} onChange={e=>{setTo(e.target.value);setPage(0);}}/></div>
 <div className="panel p-0 overflow-hidden"><Table><TableHeader><TableRow><TableHead className="pl-5">Phiếu / ngày</TableHead><TableHead className="">Nghiệp vụ</TableHead><TableHead className="">Luồng hàng</TableHead><TableHead className="">Người nhận</TableHead><TableHead className="">Số dòng</TableHead><TableHead className=""></TableHead></TableRow></TableHeader><TableBody>{list.slice(page*30,page*30+30).map(t=><TableRow key={t.id}><TableCell className="pl-5"><b className="text-sm">{t.number}</b><p className="subtle">{dt(t.date)}</p></TableCell><TableCell><span className={"pill "+(t.type==="REVERSAL"?"warn":"")}>{TYPES[t.type as TxType]}</span>{reversed.has(t.id)&&<p className="text-amber-700 text-sm mt-1">Đã đảo phiếu</p>}</TableCell><TableCell className="max-w-60 whitespace-normal text-sm">{t.from_location?location(t.from_location):t.type==="COUNT"?"Kiểm kê":t.partner||"Bên ngoài"} → {t.to_location?location(t.to_location):t.type==="DAMAGE"?"Hỏng tại khu":t.type==="SUPPLIER_RETURN"?t.partner:"Ghi giảm"}</TableCell><TableCell>{t.person||t.actor}</TableCell><TableCell className="text-right">{t.lines.length}</TableCell><TableCell><Button variant="ghost" size="sm" onClick={()=>{setSelected(t);setError("");setReason("");}}>Xem phiếu</Button></TableCell></TableRow>)}</TableBody></Table>{!list.length&&<Empty title="Chưa có phiếu phù hợp" detail="Phiếu đã xác nhận sẽ xuất hiện tại đây."/>}<div className="p-4 border-t flex justify-between items-center"><span className="subtle">{list.length} phiếu</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>Trước</Button><Button size="sm" variant="outline" disabled={(page+1)*30>=list.length} onClick={()=>setPage(page+1)}>Sau</Button></div></div></div>
 <details className="panel mt-6"><summary className="font-semibold cursor-pointer">Nhật ký thay đổi gần đây</summary><div className="divide-y mt-4">{data.events.slice(0,100).map(e=><div className="py-3 text-sm" key={e.id}><b>{Object.hasOwn(TYPES,e.kind)?TYPES[e.kind as TxType]:e.kind==="item"?"Cập nhật danh mục":e.kind==="location"?"Cập nhật khu":({supplier:"Cập nhật NCC",invoice:"Lập chứng từ mua",payment:"Trả tiền NCC",reversePayment:"Đảo thanh toán",voidInvoice:"Hủy chứng từ mua",linkReceipt:"Gắn phiếu nhập",minimum:"Cập nhật định mức"} as Record<string,string>)[e.kind]??e.kind}</b><p className="subtle">{e.actor} · {new Date(e.created_at).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"})}</p></div>)}{!data.events.length&&<p className="subtle">Chưa có thay đổi vận hành.</p>}</div></details>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="sm:max-w-4xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{selected?.number}</DialogTitle><DialogDescription>{selected&&TYPES[selected.type as TxType]} · {dt(selected?.date)}</DialogDescription></DialogHeader>{selected&&<><div className="grid sm:grid-cols-2 gap-3 text-sm"><p><b>Từ:</b> {selected.from_location?location(selected.from_location):selected.partner||"—"}</p><p><b>Đến:</b> {selected.to_location?location(selected.to_location):"—"}</p><p><b>Người nhận / thực hiện:</b> {selected.person||selected.actor}</p><p><b>Chứng từ:</b> {selected.reference||"—"}</p></div><Table><TableHeader><TableRow><TableHead className="pl-5">Hàng hóa</TableHead><TableHead className="">Số lượng</TableHead><TableHead className="">Lô / tình trạng</TableHead><TableHead className="">Thành tiền</TableHead></TableRow></TableHeader><TableBody>{selected.lines.map((l:any,i:number)=><TableRow key={i}><TableCell className="table-cell-name">{l.itemName}<p className="subtle">{l.item}</p></TableCell><TableCell className="text-right whitespace-nowrap">{qty(l.baseQuantity)} {l.baseUnit}{selected.type==="COUNT"&&<p className="subtle">Chênh: {l.difference>0?"+":""}{qty(l.difference)}</p>}</TableCell><TableCell>{l.lot||"—"}<p className="subtle">{l.condition==="damaged"?"Hỏng":"Dùng được"}{l.expiry?" · "+dt(l.expiry):""}</p></TableCell><TableCell className="text-right">{selected.type==="RECEIPT"&&!l.priceMissing?money(l.amount):"—"}</TableCell></TableRow>)}</TableBody></Table><p className="text-sm whitespace-pre-wrap">{selected.note}</p>{selected.total!==0&&<p className="font-semibold text-right">{selected.lines.some((l:any)=>l.priceMissing)?"Giá trị đã nhập (chưa đủ giá)":"Giá trị phiếu"}: {money(selected.total)}</p>}<p className="subtle">Người lập: {selected.actor} · Ghi sổ lúc {new Date(selected.created_at).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"})}</p>
 <DialogFooter className="no-print"><Button variant="outline" onClick={()=>window.print()}><Printer/> In</Button>{!["COUNT","REVERSAL"].includes(selected.type)&&!reversed.has(selected.id)&&<Button variant="outline" onClick={()=>setReverse(true)}><RotateCcw/> Đảo phiếu</Button>}</DialogFooter></>}</DialogContent></Dialog>
 <AlertDialog open={reverse} onOpenChange={setReverse}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Đảo phiếu {selected?.number}?</AlertDialogTitle><AlertDialogDescription>Tạo phiếu ngược để sửa sai và giữ nguyên lịch sử. Hệ thống sẽ kiểm tra đủ hàng trước khi ghi.</AlertDialogDescription></AlertDialogHeader><Field label="Lý do đảo phiếu *"><NoteField kind="REVERSAL" label="Lý do đảo phiếu" value={reason} onChange={setReason}/></Field>{error&&<p className="text-red-700" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Quay lại</AlertDialogCancel><AlertDialogAction disabled={busy||!reason.trim()} onClick={e=>{e.preventDefault();confirmReverse();}}>Xác nhận đảo phiếu</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
export function DataView({data}:{data:State}){
 const [search,setSearch]=useState(""),[source,setSource]=useState("all"),[page,setPage]=useState(0),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const list=data.source.history.filter((r:any)=>(source==="all"||r.source===source)&&normalize(r.values.join(" ")).includes(normalize(search)));
 async function exportData(kind:string){
  setBusy(kind);setError("");try{const response=await fetch("/api/kho?export=all"),out=await response.json() as any;if(!response.ok)throw new Error(out.error);
  if(kind==="backup")download("laka-kho-sao-luu-"+today()+".json",JSON.stringify(out,null,2),"application/json");
  if(kind==="catalog")download("danh-muc-hang-"+today()+".csv",csv([["Mã hàng","Tên hàng","Đơn vị gốc","Nhóm","Loại quản lý","Đơn vị đóng gói","Hệ số quy đổi","Đang dùng","Ghi chú"],...out.tables.items.map((i:any)=>[i.code,i.name,i.unit,i.category,KINDS[i.kind as keyof typeof KINDS],i.pack_unit,i.pack_size/1000,i.active?1:0,i.note])]),"text/csv;charset=utf-8");
  if(kind==="transactions")download("nhat-ky-kho-"+today()+".csv",csv([["Số phiếu","Ngày","Loại","Từ khu","Đến khu","Nhà cung cấp","Người nhận","Mã hàng","Tên hàng","Số lượng gốc","Đơn vị gốc","Lô","Hạn dùng","Tình trạng","Thành tiền dòng","Mã phiếu đảo","Ghi chú","Người lập","Ghi sổ lúc"],...out.tables.transactions.flatMap((t:any)=>JSON.parse(t.lines).map((l:any)=>[t.number,t.date,TYPES[t.type as TxType],out.tables.locations.find((x:any)=>x.id===t.from_location)?.name??"",out.tables.locations.find((x:any)=>x.id===t.to_location)?.name??"",t.partner,t.person,l.item,l.itemName,t.type==="REVERSAL"?-l.baseQuantity:l.baseQuantity,l.baseUnit,l.lot,l.expiry,l.condition,l.priceMissing?"":t.type==="REVERSAL"?-l.amount:l.amount,t.reversal_of??"",t.note,t.actor,t.created_at]))]),"text/csv;charset=utf-8");
  if(kind==="ledger")download("so-phat-sinh-kho-"+today()+".csv",csv([["Mã phiếu","Mã hàng","Khu","Tình trạng","Lô","Hạn dùng","Tăng / giảm","Đơn vị"],...out.tables.ledger.map((l:any)=>[out.tables.transactions.find((t:any)=>t.id===l.tx)?.number??l.tx,l.item,out.tables.locations.find((x:any)=>x.id===l.location)?.name??l.location,l.condition,l.lot,l.expiry,l.quantity/1000,out.tables.items.find((i:any)=>i.code===l.item)?.unit??""])]),"text/csv;charset=utf-8");
  }catch(e:any){setError(e.message);}finally{setBusy("");}
 }
 function legacyDate(v:any){return typeof v==="number"?dt(new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10)):String(v??"—");}
 return <><Heading title="Dữ liệu & báo cáo" detail="Xuất dữ liệu để dùng với Google Sheets, Excel hoặc lưu bản sao riêng."/>
 <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3 mb-6">{[["transactions","Phiếu nhập / xuất","Tất cả phiếu và chi tiết hàng"],["ledger","Sổ phát sinh","Tăng, giảm theo khu và lô"],["catalog","Danh mục hàng","Mã, đơn vị, loại quản lý"],["backup","Sao lưu đầy đủ","Dữ liệu, lịch sử và nhật ký"]].map(([id,title,detail])=><button className="action-card" key={id} disabled={!!busy} onClick={()=>exportData(id)}>{id==="backup"?<Database/>:<Download/>}<span><b>{busy===id?"Đang xuất…":title}</b><small className="subtle block">{detail}</small></span></button>)}</div>{error&&<p role="alert" className="text-red-700 mb-4">{error}</p>}
 <section className="panel mb-6"><h2 className="text-lg font-semibold mb-2">Làm việc với Google Sheets</h2><p className="text-sm text-muted-foreground">Xuất CSV ở trên, rồi trong Google Sheets chọn <b>Tệp → Nhập → Tải lên</b>. Chọn dấu phân cách là dấu phẩy. Sổ phát sinh có số tăng/giảm theo từng khu để đối soát. File sao lưu JSON dành cho khôi phục kỹ thuật; chưa có chức năng nhập ngược hoặc đồng bộ tự động.</p></section>
 <section className="panel mb-6"><div className="flex flex-wrap justify-between gap-4"><div><span className="eyebrow text-muted-foreground">Dữ liệu trước khi vận hành</span><h2 className="text-xl font-semibold mt-1">{data.source.title}</h2><p className="subtle mt-2">{data.source.items} mã hàng · {data.source.history.length} dòng lịch sử được giữ để tra cứu · Đọc ngày {dt(data.source.date)}</p></div>{data.source.id&&<Button variant="outline" asChild><a href={"https://docs.google.com/spreadsheets/d/"+data.source.id+"/edit"} target="_blank" rel="noreferrer"><ExternalLink/> Mở file nguồn</a></Button>}</div>
 <p className="mt-4 text-sm bg-amber-50 text-amber-900 p-4 rounded-lg">Lịch sử dưới đây không cộng vào tồn vận hành. Dữ liệu cũ còn thiếu mã hàng, nơi nhận và số dư đầu kỳ. VT022 và VT023 có cùng tên/quy cách ghi trong nguồn, cần kiểm tra trước khi gộp.</p></section>
 <div className="grid sm:grid-cols-[1fr_270px] gap-3 mb-4"><SearchBox value={search} onChange={v=>{setSearch(v);setPage(0);}} placeholder="Tìm trong lịch sử nguồn…"/><Pick label="Tab nguồn" value={source} onChange={v=>{setSource(v);setPage(0);}} options={[{value:"all",label:"Tất cả tab nguồn"},...Array.from(new Set<string>(data.source.history.map((r:any)=>r.source))).map(s=>({value:s,label:s}))]}/></div>
 <div className="panel p-0 overflow-hidden"><Table><TableHeader><TableRow><TableHead className="pl-5">Nguồn</TableHead><TableHead className="">Ngày trong nguồn</TableHead><TableHead className="">Hàng hóa</TableHead><TableHead className="">Số lượng</TableHead><TableHead className="">Thành tiền</TableHead></TableRow></TableHeader><TableBody>{list.slice(page*25,page*25+25).map((r:any)=>{
 const daily=r.source==="Nhập đồ-Hàng ngày",restaurant=r.source==="NhapKho_Nhahang",v=r.values,ni=daily||restaurant?4:3,qi=daily||restaurant?6:5,ui=daily||restaurant?5:4,ai=daily||restaurant?8:7;
 return <TableRow key={r.source+r.row}><TableCell className="pl-5 text-sm">{r.source}<p className="subtle">Dòng {r.row}</p></TableCell><TableCell>{legacyDate(v[daily?0:1])||"—"}</TableCell><TableCell className="table-cell-name">{v[ni]}<p className="subtle">{daily?"Chưa có mã hàng":v[2]||"Chưa có mã hàng"}</p></TableCell><TableCell className="text-right">{typeof v[qi]==="number"?qty(v[qi]):v[qi]} {v[ui]}</TableCell><TableCell className="text-right">{r.source==="XuatKho_PhanBo"?"—":typeof v[ai]==="number"?money(v[ai]):"—"}</TableCell></TableRow>;})}</TableBody></Table><div className="p-4 border-t flex justify-between items-center"><span className="subtle">{list.length} dòng nguồn</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={!page} onClick={()=>setPage(page-1)}>Trước</Button><Button variant="outline" size="sm" disabled={(page+1)*25>=list.length} onClick={()=>setPage(page+1)}>Sau</Button></div></div></div></>;
}
