"use client";
import {useState} from "react";
import {Plus,Pencil,ArrowRight,Download,ClipboardCheck,AlertTriangle} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Checkbox} from "@/components/ui/checkbox";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from "@/components/ui/dialog";
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from "@/components/ui/table";
import {KINDS,normalize,today,type State,type Item,type Balance,sanitizeAreaPrefix,KIND_PREFIX_MAP} from "@/lib/inventory";
import {Field,Pick,ItemPicker,SearchBox,Heading,Empty,qty,dt,download,csv} from "./kho-ui";
export function stockRows(data:State,location:string){
 return data.items.filter(i=>i.active).flatMap(item=>{
  const entries=data.balances.filter(b=>b.item===item.code&&b.location===location);
  const minimum=data.minimums.find(m=>m.item===item.code&&m.location===location)?.quantity;
  const usable=entries.filter(b=>b.condition==="usable"),total=usable.reduce((s,b)=>s+b.quantity,0),verified=usable.length>0&&usable.every(b=>b.verified_at);
  return (entries.length?entries:[{item:item.code,location,condition:"usable",lot:"",expiry:"",quantity:0,verified_at:null}]).map(b=>({...b,itemData:item,minimum,low:minimum!==undefined&&verified&&total<minimum}));
 });
}
export function InventoryView({data,onCount,onTransfer}:{data:State;onCount:any;onTransfer:any}){
 const [location,setLocation]=useState("KHO_TONG"),[usageFilter,setUsageFilter]=useState("all"),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[page,setPage]=useState(0);
 const rows=stockRows(data,location)
  .filter(r=>normalize(r.itemData.name+" "+r.item).includes(normalize(search)))
  .filter(r=>filter==="all"||filter==="unverified"&&!r.verified_at||filter==="low"&&r.low||filter==="damaged"&&r.condition==="damaged"||filter==="expiry"&&r.quantity>0&&r.expiry&&r.expiry<=new Date(Date.now()+30*86400000).toISOString().slice(0,10))
  .filter(r=>usageFilter==="all"||(usageFilter==="unassigned"?!r.itemData.usage_location:r.itemData.usage_location===usageFilter));
 const visible=rows.slice(page*40,page*40+40),loc=data.locations.find(l=>l.id===location)?.name;
 function exportStock(){
  download("ton-kho-"+location+"-"+today()+".csv",csv([["Mã hàng","Tên hàng","Khu thực tế","Khu dự kiến","Đơn vị","Lô","Hạn dùng","Tình trạng","Số lượng ghi sổ","Đã xác nhận số dư","Kiểm kê gần nhất"],...rows.map(r=>[r.item,r.itemData.name,loc,data.locations.find(l=>l.id===r.itemData.usage_location)?.name??"Chưa gán",r.itemData.unit,r.lot,r.expiry,r.condition==="usable"?"Dùng được":"Hỏng",r.quantity/1000,r.verified_at?"Có":"Chưa",r.verified_at??""])]),"text/csv;charset=utf-8");
 }
 return <><Heading title="Tồn kho theo khu" detail="Số lượng ghi sổ được cập nhật từ các phiếu đã xác nhận."><Button variant="outline" onClick={exportStock}><Download/> Xuất bảng đang xem</Button></Heading>
 <div className="grid sm:grid-cols-2 lg:grid-cols-[200px_200px_1fr_220px] gap-3 mb-5">
  <Pick label="Khu xem tồn thực tế" value={location} onChange={v=>{setLocation(v);setPage(0);}} options={data.locations.map(l=>({value:l.id,label:l.name}))}/>
  <Pick label="Khu dự kiến sử dụng" value={usageFilter} onChange={v=>{setUsageFilter(v);setPage(0);}} options={[{value:"all",label:"Tất cả khu dự kiến"},{value:"unassigned",label:"Chưa gán khu dự kiến"},...data.locations.map(l=>({value:l.id,label:l.name}))]}/>
  <SearchBox value={search} onChange={v=>{setSearch(v);setPage(0);}}/>
  <Pick label="Lọc tình trạng tồn" value={filter} onChange={v=>{setFilter(v);setPage(0);}} options={[{value:"all",label:"Tất cả mặt hàng"},{value:"unverified",label:"Chưa kiểm kê xác nhận"},{value:"low",label:"Dưới mức tối thiểu"},{value:"expiry",label:"Hết hạn / trong 30 ngày"},{value:"damaged",label:"Hỏng / chờ xử lý"}]}/>
 </div>
 <div className="panel p-0 overflow-hidden"><Table><TableHeader><TableRow><TableHead className="pl-5">Hàng hóa</TableHead><TableHead className="">Lô / hạn dùng</TableHead><TableHead className="">Tình trạng</TableHead><TableHead className="">Số lượng ghi sổ</TableHead><TableHead className="">Xác nhận số dư</TableHead><TableHead className=""></TableHead></TableRow></TableHeader><TableBody>{visible.map((r,i)=><TableRow key={i}><TableCell className="pl-5 table-cell-name"><b>{r.itemData.name}</b><p className="subtle">{r.item} · {r.itemData.category}{r.itemData.usage_location?" · Khu dự kiến: "+(data.locations.find(l=>l.id===r.itemData.usage_location)?.name||r.itemData.usage_location):" · Chưa gán khu"}</p></TableCell><TableCell>{r.lot||"—"}<p className={r.expiry&&r.expiry<today()?"text-red-700 text-sm":"subtle"}>{r.expiry?dt(r.expiry):"Không khai báo HSD"}</p></TableCell><TableCell><span className={"pill "+(r.condition==="damaged"?"bad":r.low?"warn":"")}>{r.condition==="damaged"?"Hỏng":r.low?"Cần bổ sung":"Dùng được"}</span></TableCell><TableCell className="text-right whitespace-nowrap"><strong>{r.verified_at||r.quantity!==0?qty(r.quantity/1000):"—"}</strong> {r.itemData.unit}{r.minimum!==undefined&&<p className="subtle">Mức tối thiểu: {qty(r.minimum/1000)}</p>}</TableCell><TableCell>{r.verified_at?<><span className="pill good">Đã xác nhận</span><p className="subtle mt-1">{dt(r.verified_at)}</p></>:<span className="pill warn">Chưa kiểm kê</span>}</TableCell><TableCell><div className="flex gap-1"><Button variant="ghost" size="icon" title="Kiểm kê mặt hàng" aria-label={"Kiểm kê "+r.itemData.name} onClick={()=>onCount(r)}><ClipboardCheck size={18}/></Button>{r.quantity>0&&<Button variant="ghost" size="icon" aria-label={"Chuyển "+r.itemData.name} onClick={()=>onTransfer(r)}><ArrowRight size={18}/></Button>}</div></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<Empty title="Không có mặt hàng phù hợp"/>}<div className="p-4 border-t flex flex-wrap justify-between gap-3"><span className="subtle">{rows.length} dòng · {loc}</span><div className="flex items-center gap-3"><Button variant="outline" size="sm" disabled={page===0} onClick={()=>setPage(page-1)}>Trước</Button><span className="text-sm">{page+1} / {Math.max(1,Math.ceil(rows.length/40))}</span><Button variant="outline" size="sm" disabled={(page+1)*40>=rows.length} onClick={()=>setPage(page+1)}>Sau</Button></div></div></div></>;
}
export function CatalogView({data,execute,busy}:{data:State;execute:any;busy:boolean}){
 const [search,setSearch]=useState(""),[kind,setKind]=useState("all"),[usageFilter,setUsageFilter]=useState("all"),[page,setPage]=useState(0),[edit,setEdit]=useState<any>(null),[error,setError]=useState("");
 const list=data.items.filter(i=>normalize(i.name+" "+i.code+" "+i.category).includes(normalize(search))&&(kind==="all"||i.kind===kind)&&(usageFilter==="all"||(usageFilter==="unassigned"?!i.usage_location:i.usage_location===usageFilter)));
 function open(item?:Item){
  setError("");
  if(item){
   setEdit({stableId:crypto.randomUUID(),code:item.code,name:item.name,unit:item.unit,category:item.category,kind:item.kind,usage_location:item.usage_location||"",note:item.note,active:item.active,pack_unit:item.pack_unit,packSize:item.pack_size/1000,manualCode:true,initial_quantity:"",isNew:false});
  }else{
   setEdit({stableId:crypto.randomUUID(),code:"",name:"",unit:"Cái",category:"Chung",kind:"unclassified",usage_location:"",note:"",active:1,pack_unit:"",packSize:1,manualCode:false,initial_quantity:"",initial_location:"KHO_TONG",initial_date:today(),initial_lot:"",initial_expiry:"",isNew:true});
  }
 }
 async function save(){
  try{
   const payload:any={code:edit.manualCode||!edit.isNew?edit.code.trim():"",name:edit.name.trim(),unit:edit.unit.trim()||"Cái",category:edit.category.trim()||"Chung",kind:edit.kind||"unclassified",usage_location:edit.usage_location||null,note:edit.note||"",active:edit.active,pack_unit:edit.pack_unit||"",packSize:Number(edit.packSize)||1};
   if(edit.isNew&&edit.initial_quantity!==undefined&&edit.initial_quantity!==null&&String(edit.initial_quantity).trim()!==""){
    payload.initial_quantity=edit.initial_quantity;payload.initial_location=edit.initial_location||"KHO_TONG";payload.initial_date=edit.initial_date||today();payload.initial_lot=edit.initial_lot||"";payload.initial_expiry=edit.initial_expiry||"";
   }
   await execute("item",payload,{id:edit.stableId,create:edit.isNew});
   setEdit(null);
  }catch(e:any){setError(e.message);}
 }
 const previewCode=edit?.isNew&&!edit.manualCode?sanitizeAreaPrefix(edit.usage_location)+"-"+(KIND_PREFIX_MAP[edit.kind]||"CL")+"-????":"";
 return <><Heading title="Danh mục hàng hóa" detail="Một mã cho một quy cách hàng. Giá mua được lưu theo từng phiếu."><Button onClick={()=>open()}><Plus/> Thêm mặt hàng</Button></Heading>
 <div className="grid sm:grid-cols-[1fr_200px_200px] gap-3 mb-5">
  <SearchBox value={search} onChange={v=>{setSearch(v);setPage(0);}}/>
  <Pick label="Khu dự kiến" value={usageFilter} onChange={v=>{setUsageFilter(v);setPage(0);}} options={[{value:"all",label:"Tất cả khu dự kiến"},{value:"unassigned",label:"Chưa gán khu dự kiến"},...data.locations.map(l=>({value:l.id,label:l.name}))]}/>
  <Pick label="Loại quản lý" value={kind} onChange={v=>{setKind(v);setPage(0);}} options={[{value:"all",label:"Tất cả loại quản lý"},...Object.entries(KINDS).map(([value,label])=>({value,label}))]}/>
 </div>
 <div className="panel p-0 overflow-hidden"><Table><TableHeader><TableRow><TableHead className="pl-5">Mặt hàng</TableHead><TableHead className="">Khu dự kiến</TableHead><TableHead className="">Đơn vị & quy đổi</TableHead><TableHead className="">Loại quản lý</TableHead><TableHead className="">Trạng thái</TableHead><TableHead className=""></TableHead></TableRow></TableHeader><TableBody>{list.slice(page*40,page*40+40).map(i=><TableRow key={i.code}><TableCell className="table-cell-name pl-5"><b>{i.name}</b><p className="subtle">{i.code} · {i.category}</p></TableCell><TableCell><span className="text-sm font-medium">{data.locations.find(l=>l.id===i.usage_location)?.name??"—"}</span></TableCell><TableCell>{i.unit}{i.pack_unit&&<p className="subtle">1 {i.pack_unit} = {qty(i.pack_size/1000)} {i.unit}</p>}</TableCell><TableCell><span className={"pill "+(i.kind==="unclassified"?"warn":"")}>{KINDS[i.kind]}</span></TableCell><TableCell>{i.active?"Đang dùng":"Ngừng dùng"}</TableCell><TableCell><Button variant="ghost" size="icon" aria-label={"Sửa "+i.code} onClick={()=>open(i)}><Pencil size={17}/></Button></TableCell></TableRow>)}</TableBody></Table>{!list.length&&<Empty title="Không tìm thấy mặt hàng"/>}<div className="p-4 border-t flex justify-between gap-3"><span className="subtle">{list.length} mặt hàng</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>Trước</Button><Button size="sm" variant="outline" disabled={(page+1)*40>=list.length} onClick={()=>setPage(page+1)}>Sau</Button></div></div></div>
 <Dialog open={!!edit} onOpenChange={v=>!v&&!busy&&setEdit(null)}><DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{edit?.isNew?"Thêm mặt hàng":"Cập nhật mặt hàng"}</DialogTitle><DialogDescription>{edit?.isNew?"Tạo mã hàng và có thể xác nhận số lượng ban đầu ngay tại đây.":"Mã hàng giữ nguyên để bảo toàn lịch sử."}</DialogDescription></DialogHeader>{edit&&<><div className="space-y-4">
 {edit.isNew?<div className="space-y-1"><div className="flex justify-between items-center"><span className="text-sm font-medium">Mã hàng</span><button type="button" className="text-xs text-primary underline" onClick={()=>setEdit({...edit,manualCode:!edit.manualCode})}>{edit.manualCode?"Chuyển sang tự cấp mã":"Nhập mã thủ công"}</button></div>{edit.manualCode?<Input value={edit.code} onChange={e=>setEdit({...edit,code:e.target.value})} placeholder="Ví dụ: BP-TH-0001"/>:<div className="p-2.5 rounded-md border bg-muted/40 text-sm"><span className="font-mono text-xs font-semibold">{previewCode}</span><p className="text-xs text-muted-foreground mt-0.5">Máy chủ tự động cấp mã theo khu và loại quản lý khi lưu.</p></div>}</div>:<Field label="Mã hàng"><Input disabled value={edit.code}/></Field>}
 <div className="grid sm:grid-cols-2 gap-4">
  <Field label="Tên hàng *"><Input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field>
  <Field label="Đơn vị gốc *"><Input value={edit.unit} onChange={e=>setEdit({...edit,unit:e.target.value})}/></Field>
  <Field label="Khu dự kiến sử dụng (chính)"><Pick label="Khu dự kiến sử dụng" value={edit.usage_location} onChange={v=>setEdit({...edit,usage_location:v})} options={[{value:"",label:"Chưa gán khu dự kiến"},...data.locations.filter(l=>l.active).map(l=>({value:l.id,label:l.name}))]}/></Field>
  <Field label="Nhóm hàng"><Input value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}/></Field>
  <Field label="Loại quản lý"><Pick label="Loại quản lý mặt hàng" value={edit.kind} onChange={v=>setEdit({...edit,kind:v})} options={Object.entries(KINDS).map(([value,label])=>({value,label}))}/></Field>
 </div>
 {edit.isNew&&<div className="border-t pt-4 mt-2"><div className="mb-2"><b className="text-sm">Số dư ban đầu khi tạo mã</b><p className="text-xs text-muted-foreground">Xác nhận số dư đếm thực tế (mốc kiểm kê ban đầu). Để trống nếu hiện chưa có hàng.</p></div><Field label="Số lượng ban đầu đã xác nhận" hint="Để trống nếu chưa có hàng; có thể nhập 0 để xác nhận mốc hết hàng."><Input type="number" min="0" step=".001" placeholder="Để trống nếu chưa có hàng" value={edit.initial_quantity} onChange={e=>setEdit({...edit,initial_quantity:e.target.value})}/></Field>{edit.initial_quantity!==""&&edit.initial_quantity!==undefined&&<div className="grid sm:grid-cols-2 gap-3 mt-3 p-3 bg-muted/30 rounded-lg"><Field label="Khu nhận hàng thực tế *"><Pick label="Khu nhận hàng" value={edit.initial_location} onChange={v=>setEdit({...edit,initial_location:v})} options={data.locations.filter(l=>l.active).map(l=>({value:l.id,label:l.name}))}/></Field><Field label="Ngày ghi nhận *"><Input type="date" value={edit.initial_date} onChange={e=>setEdit({...edit,initial_date:e.target.value})}/></Field><Field label="Lô hàng (tùy chọn)"><Input value={edit.initial_lot} onChange={e=>setEdit({...edit,initial_lot:e.target.value})} placeholder="Số lô"/></Field><Field label="Hạn dùng (tùy chọn)"><Input type="date" value={edit.initial_expiry} onChange={e=>setEdit({...edit,initial_expiry:e.target.value})}/></Field></div>}</div>}
 <details className="mt-2 text-sm"><summary className="cursor-pointer font-medium text-muted-foreground py-1">Tùy chọn nâng cao (quy đổi đơn vị, ghi chú)</summary><div className="space-y-3 pt-2"><div className="grid sm:grid-cols-2 gap-3"><Field label="Đơn vị đóng gói (tùy chọn)"><Input value={edit.pack_unit} onChange={e=>setEdit({...edit,pack_unit:e.target.value})} placeholder="Ví dụ: Thùng"/></Field>{edit.pack_unit&&<Field label={"1 "+edit.pack_unit+" bằng bao nhiêu "+(edit.unit||"đơn vị gốc")+"?"}><Input type="number" min=".001" step=".001" value={edit.packSize} onChange={e=>setEdit({...edit,packSize:e.target.value})}/></Field>}</div><Field label="Quy cách / ghi chú"><Textarea value={edit.note} onChange={e=>setEdit({...edit,note:e.target.value})}/></Field></div></details>
 <label className="flex gap-3 items-center text-sm"><Checkbox checked={!!edit.active} onCheckedChange={v=>setEdit({...edit,active:v?1:0})}/> Đang sử dụng</label>
 </div>{error&&<p className="text-red-700" role="alert">{error}</p>}<DialogFooter><Button variant="outline" onClick={()=>setEdit(null)} disabled={busy}>Đóng</Button><Button onClick={save} disabled={busy}>{busy?"Đang lưu…":"Lưu mặt hàng"}</Button></DialogFooter></>}</DialogContent></Dialog></>;
}
export function SettingsView({data,execute,busy}:{data:State;execute:any;busy:boolean}){
 const [location,setLocation]=useState<any>(null),[minimum,setMinimum]=useState({item:"",location:"KHO_TONG",quantity:""}),[error,setError]=useState("");
 async function saveLocation(){try{await execute("location",location);setLocation(null);setError("");}catch(e:any){setError(e.message);}}
 async function saveMinimum(){try{if(minimum.quantity==="")throw new Error("Nhập mức tồn tối thiểu.");await execute("minimum",{...minimum,quantity:Number(minimum.quantity)});setError("");}catch(e:any){setError(e.message);}}
 return <><Heading title="Thiết lập kho" detail="Quản lý khu nhận hàng và định mức. Múi giờ làm việc: Việt Nam."/><div className="grid xl:grid-cols-2 gap-6"><section className="panel"><div className="flex justify-between items-center gap-3 mb-4"><h2 className="text-xl font-semibold">Khu / vị trí</h2><Button variant="outline" size="sm" onClick={()=>{setError("");setLocation({name:"",active:1});}}><Plus/> Thêm khu</Button></div><div className="divide-y">{data.locations.map(l=><div className="flex items-center justify-between gap-3 py-3" key={l.id}><div><b>{l.name}</b><p className="subtle">{l.active?"Đang sử dụng":"Ngừng sử dụng"}</p></div><Button variant="ghost" size="icon" aria-label={"Sửa khu "+l.name} onClick={()=>{setError("");setLocation(l);}}><Pencil size={17}/></Button></div>)}</div></section><section className="panel"><h2 className="text-xl font-semibold mb-5">Mức tồn tối thiểu</h2><div className="space-y-4"><Field label="Mặt hàng"><ItemPicker items={data.items} value={minimum.item} onChange={v=>setMinimum({...minimum,item:v})}/></Field><Field label="Khu"><Pick label="Khu áp dụng định mức" value={minimum.location} onChange={v=>setMinimum({...minimum,location:v})} options={data.locations.filter(l=>l.active).map(l=>({value:l.id,label:l.name}))}/></Field><Field label={"Số lượng tối thiểu ("+(data.items.find(i=>i.code===minimum.item)?.unit??"đơn vị gốc")+")"}><Input type="number" min="0" step=".001" value={minimum.quantity} onChange={e=>setMinimum({...minimum,quantity:e.target.value})}/></Field><Button disabled={busy} onClick={saveMinimum}>Lưu mức tối thiểu</Button><p className="subtle">Cảnh báo dựa trên tổng hàng dùng được tại khu đã có số dư xác nhận.</p></div><div className="divide-y mt-5">{data.minimums.map(m=><div className="py-3 text-sm flex justify-between gap-3" key={m.item+m.location}><span>{data.items.find(i=>i.code===m.item)?.name}<small className="block text-muted-foreground">{data.locations.find(l=>l.id===m.location)?.name}</small></span><b>{qty(m.quantity/1000)} {data.items.find(i=>i.code===m.item)?.unit}</b></div>)}</div></section></div>
 <section className="panel mt-6"><h2 className="text-xl font-semibold mb-3">Quyền truy cập & cách ghi sổ</h2><p className="mb-3">Không gian riêng của người quản lý. Các phiếu lưu tên người lập và thời gian ghi nhận.</p><ul className="space-y-2 text-sm text-muted-foreground"><li>Phiếu đã ghi sổ được giữ nguyên. Sửa sai bằng phiếu đảo hoặc kiểm kê bổ sung có lý do.</li><li>Chuyển khu và chuyển sang hàng hỏng vẫn giữ tổng hàng; tiêu hao, mất/hủy và trả nhà cung cấp làm giảm số lượng.</li><li>Dữ liệu được lưu trên hệ thống. Cần kết nối mạng để tải và ghi sổ. Có thể lưu nháp trước khi xác nhận.</li><li>Google Sheets nhận dữ liệu qua file CSV xuất từ mục Dữ liệu & báo cáo; chưa có đồng bộ tự động hai chiều.</li></ul></section>
 {error&&!location&&<p className="text-red-700 mt-4" role="alert">{error}</p>}
 <Dialog open={!!location} onOpenChange={v=>!v&&!busy&&setLocation(null)}><DialogContent><DialogHeader><DialogTitle>{location?.id?"Cập nhật khu":"Thêm khu"}</DialogTitle><DialogDescription>Mỗi vị trí có số tồn riêng.</DialogDescription></DialogHeader>{location&&<><Field label="Tên khu"><Input value={location.name} onChange={e=>setLocation({...location,name:e.target.value})}/></Field><label className="flex gap-3 items-center"><Checkbox checked={!!location.active} onCheckedChange={v=>setLocation({...location,active:v?1:0})}/> Đang sử dụng</label>{error&&<p role="alert" className="text-red-700">{error}</p>}<DialogFooter><Button onClick={saveLocation} disabled={busy}>Lưu khu</Button></DialogFooter></>}</DialogContent></Dialog></>;
}
