import fs from "node:fs";import path from "node:path";import {spawnSync} from "node:child_process";import {createHash} from "node:crypto";
const commit=process.env.GITHUB_SHA||spawnSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).stdout.trim();if(!/^[a-f0-9]{40}$/.test(commit))throw Error("A full Git commit is required");
const root=path.resolve("artifacts"),out=path.join(root,"release-"+commit);if(fs.existsSync(out))throw Error("Release folder exists; choose a fresh build workspace");
fs.mkdirSync(out,{recursive:true});fs.cpSync(".next/standalone",out,{recursive:true});fs.cpSync(".next/static",path.join(out,".next/static"),{recursive:true});fs.cpSync("public",path.join(out,"public"),{recursive:true});
for(const name of ["drizzle","deploy"])fs.cpSync(name,path.join(out,name),{recursive:true});
fs.mkdirSync(path.join(out,"scripts"),{recursive:true});for(const name of ["migrate-sqlite.mjs","backup-sqlite.mjs","manage-owner.mjs","import-source-opening.mjs"])fs.copyFileSync(path.join("scripts",name),path.join(out,"scripts",name));
fs.mkdirSync(path.join(out,"lib"),{recursive:true});for(const name of ["auth-core.ts","inventory.ts","auto-code.ts"])fs.copyFileSync(path.join("lib",name),path.join(out,"lib",name));
fs.writeFileSync(path.join(out,"RELEASE"),commit+"\n");
function scan(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,item.name),relative=path.relative(out,full).replaceAll("\\","/");if(/(^|\/)(\.git|\.sites-runtime|\.wrangler|data|backups|outputs)(\/|$)/.test(relative)&&!relative.startsWith("node_modules/"))throw Error("Private path in package: "+relative);if(/(^|\/)(owner\.json|viewers\.json|source-data\.json|\.env(?:\..*)?|.*\.(?:sqlite|pem|key))$/.test(relative))throw Error("Private file in package: "+relative);if(item.isDirectory())scan(full);}}
scan(out);const archive=path.join(root,"laka-warehouse.tgz"),tar=process.platform==="win32"?"C:/Windows/System32/tar.exe":"tar";const r=spawnSync(tar,["-czf",archive,"-C",out,"."],{stdio:"inherit"});if(r.status!==0)throw Error("Archive failed");const sha=createHash("sha256").update(fs.readFileSync(archive)).digest("hex");fs.writeFileSync(archive+".sha256",sha+"  laka-warehouse.tgz\n");console.log(JSON.stringify({commit,archive,sha256:sha,bytes:fs.statSync(archive).size}));
